### ISSUE TITLE
AW3821DW support

### ISSUE THREAD

**Issue by someoneelsehere** [T-Troll/alienfx-tools#109]
Similar to https://github.com/T-Troll/alienfx-tools/issues/56 ('AW3420DW support'), I have an AW3821DW and would like to assist where possible in order to achieve responsive ambient lighting i.e. detecting on-screen zone colours and matching the rear lights to these as close to real-time as possible with minimal latency.

Please let me know how I can contribute! Thanks.

**Comment by T-Troll** [comment]
Yes, you can.

As you understand, i don't have this monitor, and the guy who help me at initial stage is busy and can't do it anymore.

I RE interface, but it's tricky and don't work for now. I need more testing at real device.
So i will appreciate if you join the testing and help me to finish implementation.

The next step we need to check is why command interface fails on device.
So can you please:
- Install [USBPcap ](https://desowin.org/usbpcap/)(USB protocol grabber).
- Stop AWCCService
- Run USBPcap, select hub there monitor USB device located, define file name for log
- Run the latest sample app from #56
- Stop USBPcap
- Send me the log file

PS: I think it will be better if we continue at #56.
