### ISSUE TITLE
no lights detected 15 R4

### ISSUE THREAD

**Issue by gamerjag** [T-Troll/alienfx-tools#116]
no lights detected when i launch the program i tried this as a last resort because awcc won’t turn on my lights neither, they all went black after i reinstalled awcc with “go dark” on

**Comment by T-Troll** [comment]
My apps are universal, and it's not possible to auto-detect all versions of hardware (especially one published after release).
I can have a small database from volunteers used to auto-assign known systems.
If your system not into this database, you always have an option to define light manually.

But R4 IS into it.

So what happened - is any devices (you should have 2 of them) detected, or you have warning about no devices?

**Comment by T-Troll** [comment]
No feedback, closed.
