### ISSUE TITLE
An option to choose to check update automatically or manually is needed

### ISSUE THREAD

**Issue by takecmd** [T-Troll/alienfx-tools#121]
Just as the title says, the notification of updates is annoying.

**Comment by T-Troll** [comment]
Ok, i'll add it into next release.

I need to mention you are the first guy how complain about it after 2 years of development, what's why no such option yet. ^_^

**Comment by T-Troll** [comment]
Check [Release 5.5.7](https://github.com/T-Troll/alienfx-tools/releases/tag/5.5.7)
Please close this issue if it what you want.
