### ISSUE TITLE
Fan control not working

### ISSUE THREAD

**Issue by Hellohi3654** [T-Troll/alienfx-tools#138]
**Describe the bug**
Alien fan control has stopped working

![image](https://user-images.githubusercontent.com/57390764/168458257-8619c65a-0d54-48f7-9a44-bcdf36c76da8.png)

I just restarted my computer and now it's decided not to work
My laptop didn't update or anything

I have tried 5.9.1, 5.9.2 and 5.9.3 
They all have the same result

My friend who also has the same laptop is experiencing this problem as well

**Comment by T-Troll** [comment]
As described [here](https://github.com/T-Troll/alienfx-tools/issues/114), it can be resulted of Microsoft antivirus update - it broke some files at installation.
Try not to use installer, but download and unpack .zip file.
If this didn't help, try 5.5.5 (from zip).

**Comment by Hellohi3654** [comment]
> As described [here](https://github.com/T-Troll/alienfx-tools/issues/114), it can be resulted of Microsoft antivirus update - it broke some files at installation. Try not to use installer, but download and unpack .zip file. If this didn't help, try 5.5.5 (from zip).

I always use the zip version

version 5.5.5.1 and 5.5.4 doesn't work either

**Comment by Hellohi3654** [comment]
The bug is weird
My fan control has decided to work now on 5.9.3 not really sure why

**Comment by T-Troll** [comment]
Ok, i close this bug, but just for remark.

Fan control can not start by, mainly, two reasons:
1. Fail to load hardware driver. I use hack-way to do so (i don't want to pay every year for signature), so some system settings and antivirus can interfere. First check it (what do you have in Update->Security, disable antivirus).
2. Driver loaded, but gear not detected (so i don't know how to control it). This can happen if i change something into fan SDK, so it only depends on new release. And, of course, i check it every release at all gear i have at home.

If Microsoft does something weird in update (both OS and AV) - it can trigger reason 1.
If Dell releases new BIOS - it can trigger reason 2.

**Comment by Hellohi3654** [comment]
The fan control has been working fine today but yesterday it wasn't working
at all
Seems very random when it decides not to work
