### ISSUE TITLE
KDL.DLL listed as trojan 

### ISSUE THREAD

**Issue by thelawrencearm** [T-Troll/alienfx-tools#172]
**Describe the bug**
Switched to BIOS detection and Cylance killed the dll.  VirusTotal lists it as a trojan 

https://www.virustotal.com/gui/file/cb3992b567e9e3e147922b43a0e4d542c53c8548aba5038b70281c024b2510a9/detection

**To Reproduce**
Open AlienFX
Click Use Bios Sensors

**Expected behavior**
It should work. 

**Screenshots**

![image](https://user-images.githubusercontent.com/20508294/184151279-ddf3b505-50d9-4cd1-9483-2d94c9354c4d.png)

![image](https://user-images.githubusercontent.com/20508294/184151319-7b64a937-9e6f-4af5-a3ef-62bcff8d68a9.png)

**System (please complete the following information):**
Alienware X14

**Comment by T-Troll** [comment]
This fact mentioned into both package and git readme.
Please read this - https://github.com/T-Troll/alienfx-tools/wiki/Why-antivirus-complain-about-some-alienfx-tools-components%3F

PS: Of course, it's not a trojan.
