### ISSUE TITLE
7.0.0 version AlienFan-GUI cannot start with Windows

### ISSUE THREAD

**Issue by SDM855** [T-Troll/alienfx-tools#174]
I was on the 6.4.3.2 version, and it starts with Windows fine. However, I updated the 7.0.0 version today, and it seems it can no longer run at startup.
I tried adding it to startup listings / disabling UAC / fully uninstalling and reinstalling. Unfortunately, it still cannot run at startup.
As I reverted to the 6.4.3.2 version, it works fine again.
Do you have any ideas or suggestions about this? Thank you very much!

**System**
 - Model: m15 r7
 - OS: Windows 11 stable

**Comment by T-Troll** [comment]
Well... I found a bug preventing add start entry, but it should not interfere if already added.

First, what tool not start?
Second, open Task Scheduler and check entry with the name of the tool. Does it exist?

**Comment by SDM855** [comment]
> Well... I found a bug preventing add start entry, but it should not interfere if already added.
> 
> First, what tool not start? Second, open Task Scheduler and check entry with the name of the tool. Does it exist?

The Alienware Fan Control. It is in the Task Scheduler but still won't boot on the 7.0.0 version.

**Comment by T-Troll** [comment]
Kind of a mystery - it starts well for me.
Hmm... Do you install 6 and 7 into different folders?

**Comment by SDM855** [comment]
It is the same folder. A mystery to me as well.

**Comment by T-Troll** [comment]
Can you, please:
1. Check Task Scheduler entry (Alienfan-gui) - what in "Actions"?
2. Check Windows event logs about something related (app crash, task scheduler fail...)?
3. Start v7, then disable "Start with Windows" and enable it back?

**Comment by mario6714** [comment]
I have the same issue, i check in settings "Start with windows" and i think is not working, "alienfan-gui
![as](https://user-images.githubusercontent.com/32179719/184905155-ed3c4dd0-b027-48d9-9195-713f1378c4ab.png)
"

**Comment by T-Troll** [comment]
Yes, it was a bug which prevent enable this functions (it can't create TS entry, fix will be today). But topic starter tells he has entry in TS, but app still not start.

**Comment by mario6714** [comment]
Yes, i created the task but just ran a system level (the app is open but i cant open the gui to modify the options) i think, and if you open you will have two exe open in the same time

**Comment by T-Troll** [comment]
Check [7.0.1](https://github.com/T-Troll/alienfx-tools/releases/tag/7.0.1) - it should fix it. But first disable "Start with Windows" then enable it back.

**Comment by mario6714** [comment]
My entry is already removed

**Comment by T-Troll** [comment]
Did it start now correctly?

**Comment by mario6714** [comment]
Sorry for the late answer, Yes

**Comment by T-Troll** [comment]
Great.
