### ISSUE TITLE
GUI app freezes and exits on G7 7790

### ISSUE THREAD

**Issue by alexmurari** [T-Troll/alienfx-tools#179]
**Describe the bug**
GUI application opens, freezes for 2~3 seconds and exits.

**To Reproduce**
1. Open the `alienfx-gui.exe` app
2. The app freezes and exits.

**Expected behavior**
The app to work.

**Screenshots**

Version 7.0.0

![image](https://user-images.githubusercontent.com/11204378/185766176-0a5f4b1c-260b-4db1-8517-bea8a2437874.png)

Screenshot from version 7.0.2.1

![image](https://user-images.githubusercontent.com/11204378/185766262-f3ef1255-1dbb-4d3a-b160-70c8ea203f31.png)

**System:**
 - Model:  Dell G7 7790 (i7-9750h)
 - OS: Windows 10 21H2

**Comment by T-Troll** [comment]
Yes, i can reproduce it.

Will release hotfix ASAP (today, i hope).

**Comment by T-Troll** [comment]
Check [7.0.2.2](https://github.com/T-Troll/alienfx-tools/releases/tag/7.0.2.2).

In case it still not work for you, please open regedit and export some registry entries for me:
- `HKCU\Software\AlienFX_SDK`
- `HKCU\Software\Alienfxgui`

**Comment by alexmurari** [comment]
@T-Troll Tested, still doesn't work.

Here are the registry entries.

[alien-registries.zip](https://github.com/T-Troll/alienfx-tools/files/9388220/alien-registries.zip)

**Comment by T-Troll** [comment]
Aha, i see. 
You have incorrect data in configuration.... Now i think how can you create this combination...
Do you play with zones?

PS: You can just delete alienfangui tree and app will start.

**Comment by alexmurari** [comment]
@T-Troll Yes, I deleted and it started working again, thank you!

I think it's solved then.

I have one more question to you, but i'll ask in our discussion thread... hehe

**Comment by T-Troll** [comment]
Hold on!

This can return any time!

I need to know, how do you create this mess in configuration?
What happened at first app start and what you do?

**Comment by alexmurari** [comment]
@T-Troll I was messing around in the GUI... Switching tabs (Lights, Fans and Power, etc.), getting familiar with the app.

(Altough my Dell is a G7 7790, I selected the Dell G5 5515 when the app started)

I tried to define some zones...then when I switched to the `settings` tab, there the GUI froze and the app exited.

**Comment by alexmurari** [comment]
@T-Troll Funny enough, the zones in my keyboard were detected only when I selected the "Alienware Aurora R12" profile...
And they were detected all wrong (the left keyboard zone was detected as "power button" or something like that...)

**Comment by T-Troll** [comment]
> I tried to define some zones...then when I switched to the settings tab, there the GUI froze and the app exited.

Got it!

DO NOT use zones from different devices! They can have the same ID as some of yours, but different settings!
BTW, Aurora have IDs 0 and 1. How do you miss it into CLI?

**Comment by alexmurari** [comment]
@T-Troll

Here is how it went:

First i opened the GUI, selected G5 5515 (the other options were Alienwares, and my notebook is a G7... It was the most _logical_ choice...).

Then the CLI probe only detected 2 zones (and the probe tried to turn on IDs 0, 1, 2, 3), but only 0 and 2 turned on.

Then in the GUI I selected the Autora R12.

Executing probe again, IDs 0, 1, 2 and 3 all got light up correctly (but with wrong names).

**Comment by T-Troll** [comment]
Oh, let me guess....
1. You create light at Devices
2. You switch on Lights and create a zone and set color
3. You switch to devices and remove light
4. App crashes

Am i right?

**Comment by alexmurari** [comment]
@T-Troll Yeah, I think so! I was a bit confused trying to figure out using the app hehehe.

I just messed around.

**Comment by alexmurari** [comment]
What I dont understand is: probe with G5 profile doesn't light up all keyboard zones, but probe ater selecting Aurora R12 detects all ones correctly. (And both of them try to detect the same device IDs...) 🤔

**Comment by T-Troll** [comment]
So, this is a bug (but about other), but you should NOT read a warning at the top of EVERY release to make this!
Yes, app require some basic concept understanding. I warn about it and provide a beginner's tutorial.

As i said, using mapping from other model (which use the same chip) is a bad idea. Now you have mess in configuration, it can be solved in UI, but with effort!

I check CLI as well. Do you have AWCCService stopped?

**Comment by alexmurari** [comment]
I don't have AWCC, I uninstalled it completelly (the last version was leaking memory).

**Comment by T-Troll** [comment]
I check cli probe with same chip and empty configuration. It works correctly.
Seems like you still have some AWCC remains, like AWCCService.

**Comment by alexmurari** [comment]
@T-Troll I don't have AWCC anymore, I uninstalled it and deleted all folders related to it.

![image](https://user-images.githubusercontent.com/11204378/185801496-540064b0-bf59-4ac4-b8d2-d7c8033662d9.png)

I think that the first time i launched the GUI and selected G5 5515 caused all the trouble and errors. so it was my mistake...

**Comment by alexmurari** [comment]
I deleted all registry entries related to alienfx... and restarted the GUI, everything clean.

This are the options:

![image](https://user-images.githubusercontent.com/11204378/185801667-2de9d63a-a837-4e14-b099-f6c92d5504b4.png)

It's kinda hard for someone who owns a G7 to select anything other than the G5 profile...

**Comment by alexmurari** [comment]
With everything clean, I started the GUI and didn't select any profile (just closed the dialog), but no lights turn on, I try to cycle through the lights, but no lights turn on...

![image](https://user-images.githubusercontent.com/11204378/185802897-b8f93f8b-1436-4be1-a2c6-59510ec958a5.png)

Same thing on the CLI, `probe` command doesn't turn on any lights... nothing.

![image](https://user-images.githubusercontent.com/11204378/185803014-2db34163-d969-4734-a133-beab114f1de0.png)

The only way to make all the keyboard lights in my keyboard to turn on is to start the GUI and select the `Aurora R12` profile, after that, the GUI and probe can turn on my keyboard lights.

**Comment by alexmurari** [comment]
Actually, the profile that works is the **Alienware m15R1**, not Aurora, I tested again.

![image](https://user-images.githubusercontent.com/11204378/185803732-de0df032-0004-42b3-9da1-8e7372e73b67.png)

Now my keyboard starts to light up....

**Comment by T-Troll** [comment]
The only difference between some lights set, and no lights set in GUI is GUI turn OTHER lights black if defined, keeping selected only. And don't touch other lights, if it is not defined.
CLI always works with active light only.

As i told you, using other hardware profiles is tricky. For m15R1, for example, light 1 set to hardware power button IN CHIP as a result. You can not resolve it by AWCC, my tools only. And removing settings doesn't alter it.

**Comment by alexmurari** [comment]
@T-Troll i dont understand, without selecting the m15R1, It doesnt work. The lights wont turn on. Empty configuration doesnt work.

Is there a way to create profile from empty configuration?

**Comment by T-Troll** [comment]
I check empty configuration WITH THE SAME CHIP.
Both CLI and GUI work correctly.

Do you read beginner's guide? It's about how to set lights from scratch as well!

**Comment by alexmurari** [comment]
@T-Troll Yes, I read, specifically this part: https://github.com/T-Troll/alienfx-tools/wiki/How-to-start-(Beginner's-guide)-for-release-v6.x.x.x#assign-lights-to-grids

Assingn lights to grid via GUI, did not work, no lights turned on.

Assign lights via CLI with `probe=l,255` command, did not work, no lights turned on.

I really don't know what i'm doing wrong... i'm following your guide...

![image](https://user-images.githubusercontent.com/11204378/185818734-9fb7affc-7984-426b-98c5-ece9f91df093.png)
