### ISSUE TITLE
Is the overboost option safe?

### ISSUE THREAD

**Issue by t3dium** [T-Troll/alienfx-tools#181]
Does it overclock the fans? My cpu cooler used to get around 4800 rpm without it and now its able to reach 6700rpm which is a very significant increase.

**Comment by T-Troll** [comment]
Yes. "Overboost" about it.
Also, without app, AWCC can set different thermal profile with other fan settings (lower, than manual mode).

**Comment by t3dium** [comment]
Is it possible to reset fan curves back to normal or remove the overboost setting
![image](https://user-images.githubusercontent.com/83690012/185903665-57b9b9d5-3068-4f52-9a25-3b5a77f3f9b2.png)

I'm assuming if i make a flat-line at temp 0, boost 0, that'll use the stock fan curve?

**Comment by T-Troll** [comment]
Use "X" button on top of the fan list.

PS: Stock is 0-0 curve.

**Comment by t3dium** [comment]
Perfect, thank you. And if i were to keep the overboost, this won't blow the fans quicker in the long run?

**Comment by T-Troll** [comment]
No. Performance mode do the same.
