### ISSUE TITLE
Introduce Hysteresis to Fan Control

### ISSUE THREAD

**Issue by TheSQLGuru** [T-Troll/alienfx-tools#185]
When using curves to control the fan speed, the fans "hunt" - i.e. change speeds rapidly up and down in small increments in an attempt to keep an "exact" temperature. 

It would be much better to introduce hysteresis to fan control, such that the temp can vary small amounts (preferably user configurable amount) without changing the fan speed. Proper use of this feature would see the fans remain at a constant speed for the vast majority of time that users are using their computer as a "daily driver", which is what I do well over 90% of the time these days. 

I do not know if the same thing happens when using the (fixed??) Power Levels in the drop down menu. If they do cycle, as opposed to simply being fixed speeds, then they too should have hysteresis implemented. 

It is possible that long-term cycling of fan speeds could introduce additional wear. But the hunting of the fans is definitely audibly annoying when using the laptop, at least to me.

[https://en.wikipedia.org/wiki/Hysteresis](url)

**Comment by T-Troll** [comment]
I know about it and use it in some situations.

But it's a subject to discuss - i like faster fan reaction in middle values, it provides me audible indicator of the system load.

**Comment by TheSQLGuru** [comment]
I have ThrottleStop running 24/7 and it is set to display the CPU package temp and CPU frequency in my Task Bar. Those are my indicators of system load if I care about them - which I almost never do. The fan cycling is always providing input that is difficult to ignore/filter out. 

Since you are already familiar with hysteresis I am hopeful that you can easily implement it. Simple settings to Enable/Disable it (at least globally, if not per Power Level - but it definitely needs to be enabled for Manual mode), and a nice-to-have would be to be able to set the number of degrees above/below whatever the midpoint of the fan/temp point is at.

**Comment by T-Troll** [comment]
I've thought about it, and i configure out this will provide worse results.

The most hard case is fast temperature grow, and fans should react to it ASAP. Hysteresis will make reaction slower.
For temperature loss, it's implemented already (but for other reasons - to prevent high spin down if it was short-time loading decrease).

**Comment by TheSQLGuru** [comment]
I don't know your code yet. But a hysteresis-based temp/fan control mode should not introduce a delay in responding to a fast, and large temperature increase (the obvious worst case to respond to), as that by definition jumps well outside of whatever shape you may have implemented in the control logic. As soon as you are outside of the boundaries of that shape, which should be detectable in some few milliseconds, you simply respond to the new temperature immediately with normal curve response. You would only (re)implement hysteresis once the temperature stabilizes inside your shape for some period of time. 

In a past life worked with quite a lot of controllers, both analog and digital, and they would all respond this way in some form or another. And more than a few of these sytems were safety-clamping, over-power, protection mechanisms. 

Having said all of that, I do understand that this could easily be more work - and potential risks for flaws that could cause negative consequences - than the benefits such an implementation would provide. 

I will implement your workaround, and put some level-offs around various temperature points in my manual configuration.  Thanks for the tip! That will be pretty easy for me to do, since while I am working my laptop spends the vast majority of its time waffling around 46 +-1 deg C. :-D

**Comment by T-Troll** [comment]
All hardware implementations are different, you know.
And people too - some want it cool, some want it quiet.
So i want to keep app flexible enough for all of them.

BTW, your system is quite hot - i'm between 40 and 45 for simple tasks like browsing/coding. However, i live in tropics, so 30+ ambient.

**Comment by TheSQLGuru** [comment]
Hardware, and people, are most certainly widely-varied!

I live in the southeast part of the US, where it is very hot and humid for a good part of the year. Currently the inside temp is set at 78F/26C. Yes, the X17s do tend to run hot, especially with the 11980HK in them. And this is with a -0.06 undervolt on CPU and other CPU-power limiting controls set too. I do keep my fans low though - 2300/2100/800/600 at the moment. I am certain that my CPU is poorly pasted, and there are probably some padding issues too with the cooling system in general. Under maximum load my CPU has a 19degC delta between hottest and coolest cores. It is on my TODO list to do a tear-down and repaste both the CPU and GPU, using LM for the CPU.

**Comment by T-Troll** [comment]
> I am certain that my CPU is poorly pasted

Yes, Dell's default compound is definitely not the best one. I use ThermalTake one, this help a lot.

>  my CPU has a 19degC delta between hottest and coolest cores

Another point to the poor compound - it should be less difference.

> using LM

A bit dangerous. Better try a decent compound first and look at results - it can be enough. You don't have enough power to overclock GPU anyway.

**Comment by TheSQLGuru** [comment]
I have studied posts and videos by others on how to safely do the LM, so I think I can manage it. I may still not go with it though, as just getting to the damn CPU/GPU in the X17 is rather a PITA. And with LM I would have to do it at least one more time, likely more. 

I am curious why you think I don't have enough power to OC the CPU. The X17 has a 330W power brick, and I have Intel's power sharing stuff disabled. 125 for CPU and 150/165 for CPU still leaves room for other components. And with both the CPU and GPU undervolted, the power draw will be a fair bit lower for equal clock speeds, allowing for an overclock on both. HEAT is the most difficult thing to overcome on these laptops. And I can't do any more about that until I have the time and will power to do the repaste evolutions. 

There is also a BIOS hack that will force the CPU to report 1W of power draw, which allows for full wattage all the time to the GPU. I won't bother with that until after I do the repaste.
