### ISSUE TITLE
Taskbar Tray Icon Right-Click Crashes Fan Control

### ISSUE THREAD

**Issue by TheSQLGuru** [T-Troll/alienfx-tools#189]
Win 10 x64 21H2 fully patched. App version v7.0.3

When the app has been minimized to the tray, a right-click (hoping to be able to change power modes - reference the feature request I just made) caused the app to crash.

This is repeatable.

**Comment by TheSQLGuru** [comment]
I realize that the app may not be "crashing" but may rather just be "exiting gracefully - just unexpectedly". :-D

**Comment by T-Troll** [comment]
Read `Alienfan-GUI` manual - it works as designed for now. Right click on tray menu close app.

**Comment by TheSQLGuru** [comment]
Well, this item is moot now anyway, because a tray icon right-click now opens the dialog that allows changing the power level. Which is good, because right-click to close a tray app is VERY non-standard! :-D

**Comment by T-Troll** [comment]
No, it's quite common for menu-less apps.
