### ISSUE TITLE
The app wont start corretely after enable the option "Start with Windows" in Alienfx-gui.exe

### ISSUE THREAD

**Issue by mario6714** [T-Troll/alienfx-tools#190]
**Describe the bug**

**To Reproduce**
1. Go to 'Open Alienfx-gui.exe and tab settings'
2. Click on 'Start with Windows'

**Expected behavior**
The icon in the tray for make changes or update the configuration in the app

**Screenshots**

![imagen](https://user-images.githubusercontent.com/32179719/187117947-5b9b92a8-2c7d-486e-9d8b-3d3f063728c0.png)
![imagen](https://user-images.githubusercontent.com/32179719/187117973-70be8c71-96c6-4bdd-aac7-202b1d945b08.png)

**System (please complete the following information):**
 - Model: Dell G15 5510
 - Model details: [e.g. per-key rgb keyboard]
 - OS: Windows 11 Pro Version 21H2 22000.856

**Additional context**

**Comment by mario6714** [comment]
Update: I just enabled "start with windows" in alienfx-gui.exe and disabled the option "start with windows" in Alienfx-gui.exe and reboot like 3 times and the app alienfx-gui.exe starts fine

**Comment by mario6714** [comment]
Update: I just enabled "start with windows" in alienfan-gui.exe and disabled the option "start with windows" in Alienfx-gui.exe and reboot like 3 times and the app alienfan-gui.exe starts fine

**Comment by T-Troll** [comment]
Seems like you use bugged set (first 7.0.0 have a bug there) and don't read release notes for fix - i recommend to do this into it.

**Comment by mario6714** [comment]
This?

Application behavior control block at right:

    "Start with Windows" - Start application at Windows start. It will not work if application request run as admin level (see below) (default - off).
