### ISSUE TITLE
GMode dont work

### ISSUE THREAD

**Issue by mario6714** [T-Troll/alienfx-tools#191]
**Describe the bug**
G-Mode don't work after i enable G-Mode in the app

**To Reproduce**
1. Go to 'alienfx-gui.exe in tab "Fans and Power" or in alienfan-gui.exe'
2. Click on 'G-Mode'

**Expected behavior**

**Screenshots**

![imagen](https://user-images.githubusercontent.com/32179719/187118276-74577604-4979-4d30-b18e-50e4a7526bf2.png)
![imagen](https://user-images.githubusercontent.com/32179719/187118636-29909cff-554d-4b66-a39d-18ac15dd2276.png)

**System (please complete the following information):**
 - Model: Dell G15 5510
 - Model details: [e.g. per-key rgb keyboard]
 - OS: Windows 11 Pro 21H2 22000.856

**Additional context**

**Comment by T-Troll** [comment]
Please download this CLI - [alienfan-cli.zip](https://github.com/T-Troll/alienfx-tools/files/9441618/alienfan-cli.zip)
Unpack it, open administrator CMD and run `alienfan-cli.exe test=2,2 test=3,2`.
Share output with me.

**Comment by mario6714** [comment]
Here:

C:\alienfx-tool\Test>alienfan-cli.exe test=2,2 test=3,2
AlienFan-CLI v7.0.2.1
Supported hardware detected, 2 fans, 9 sensors, 5 power states, G-Mode.
command 2 arg 2 - result 2933
command 3 arg 2 - result 1200

**Comment by mario6714** [comment]
C:\alienfx-tool\Test>alienfan-cli.exe test=2,2 test=3,2.
AlienFan-CLI v7.0.2.1
Supported hardware detected, 2 fans, 9 sensors, 5 power states, G-Mode.
command 2 arg 2 - result 2933
command 3 arg 2 - result 1200

**Comment by T-Troll** [comment]
Check this version: [alienfan-gui.zip](https://github.com/T-Troll/alienfx-tools/files/9448287/alienfan-gui.zip)
Did it work now?

**Comment by mario6714** [comment]
I think yes, thanks, what was the problem?

![imagen](https://user-images.githubusercontent.com/32179719/187311715-3e58a54c-904d-4ce8-bffa-9d6e9c4964ff.png)

**Comment by T-Troll** [comment]
Not a problem, but a bug into your BIOS. I'll override it.

Wait for next release to update FX GUI as well.

**Comment by mario6714** [comment]
Ohh, help if i reinstall the latest version of bios? or i need install a old version?

Ok, for the moment i am going to use only alienfan-gui, thanks.

**Comment by T-Troll** [comment]
> Ohh, help if i reinstall the latest version of bios? or i need install a old version?

No. It's just work this way for your system.
