### ISSUE TITLE
Craches on startup

### ISSUE THREAD

**Issue by brunosalezze** [T-Troll/alienfx-tools#195]
**Describe the bug**
The app craches on startup.

**System (please complete the following information):**
 - Model: Dell G15 5525 Ryzen
 - Model details:  per-key rgb keyboard
 - OS: Windows 11 stable

**Additional context**
I was able to start the app and see the GUI once, but crached and did not load again. How do I delete the config file?

**Comment by brunosalezze** [comment]
Sorry Its a G15 5515 AMD Edition.
The keyboard actually is a 4 zone one. 
The only app I am having issues with is Control, the other ones work great!
I was able to open the app again deleting the registry keys.
How can I help for my device to be suported in future releases?

**Comment by T-Troll** [comment]
Oh... I'we as you to share config to me first - i need to pinpoint and fix this! %-(

Make all lights and grids first, then press "Save lights and grids" button and share .csv file with me. I'll add it into device database next release.
