### ISSUE TITLE
Startup delay option

### ISSUE THREAD

**Issue by DinnerBug** [T-Troll/alienfx-tools#214]
**Is your feature request related to a problem? Please describe.**
I based my fan curve off of the gpu core temperature which is only available after running Libre Hardware Monitor. I have Alien FX control and Libre Hardware Monitor set to "Start with Windows" but Alien FX control always starts faster whan Libre Hardware Monitor and so the sensors arent's detected and can't be used.

**Describe the solution you'd like**
I would like the program to only start after Libre Hardware Monitor so maybe add a startup delay option

**System (please complete the following information):**
 - Model: Alienware Aurora r8
 - Model details: egb on the pc case only
 - OS: Windows 10 home

**Additional context**

Thank you :)

**Comment by T-Troll** [comment]
I have this option before (for driver load delay), so i just return it back.
Thank you to point it, wait until next release beta.

**Comment by DinnerBug** [comment]
Your are a king. Thank you and have a nice day.

**Comment by T-Troll** [comment]
Hold on!
First i need to implement it (and you check), then close this issue after release.

**Comment by DinnerBug** [comment]
oh, ok

**Comment by T-Troll** [comment]
Check this one - [alienfx-tools.zip](https://github.com/T-Troll/alienfx-tools/files/9742913/alienfx-tools.zip).
How it works - add delay in seconds into command line (like `alienfx-gui.exe 5` for 5 seconds init delay). All GUI apps support this option.

**Comment by DinnerBug** [comment]
Hey, it works, but I get a Windows prompt to authorize the program.

**Comment by DinnerBug** [comment]
![Screenshot 2022-10-10 175732](https://user-images.githubusercontent.com/75734620/194920524-a199b565-cfcc-4d0e-97cc-ab7ccbf2d072.png)
![Screenshot 2022-10-10 175905](https://user-images.githubusercontent.com/75734620/194920536-0397b172-42d7-463f-b469-57efa10c5a22.png)
![Screenshot 2022-10-10 175936](https://user-images.githubusercontent.com/75734620/194920544-3c0821b7-068e-456e-8f2a-53d058cbab25.png)
![Screenshot 2022-10-10 180017](https://user-images.githubusercontent.com/75734620/194920560-411abe4e-efe6-47b3-bdc1-0ca62c715e70.png)
![Screenshot 2022-10-10 180053](https://user-images.githubusercontent.com/75734620/194920566-b03e3769-1a45-453f-a534-0ab1535e8b11.png)

**Comment by DinnerBug** [comment]
Thanks to your help I've been able to figure it out. I'm leaving instructions here (if that's ok with you) in case someone else who doesn't read "README"s swings by the solved issues section.

- In AlienFX Control enable "Start with Windows"
- Open Task Scheduler
- Task Scheduler Library > right click AlienFX-GUI > Properties
![Screenshot 2022-10-10 175905](https://user-images.githubusercontent.com/75734620/194929329-71ffdeec-27d2-49f1-8a23-cf303ee9a4ad.png)

- Triggers > At log on > Edit
![Screenshot 2022-10-10 175936](https://user-images.githubusercontent.com/75734620/194929504-7edba515-5b0a-4010-af16-1c38f471bdac.png)

- Enable "Delay task for" and choose how long after logging in the program will start.
![Screenshot 2022-10-10 180053](https://user-images.githubusercontent.com/75734620/194929636-b2e272e9-dcbf-4f32-80ad-1ae1c007d76a.png)

- Save

**Comment by T-Troll** [comment]
Thank you for log, i'll use parts of it in manual.
But there is one issue - "Task delay" unstable into Windows 10.
So more solid way is "Actions"->"Edit"->Add delay into "Arguments" field.

**Comment by DinnerBug** [comment]
Ok, I'll change that, thank you again.
