### ISSUE TITLE
Save button missing?

### ISSUE THREAD

**Issue by NoxaNM15R5** [T-Troll/alienfx-tools#220]
Thank you for this beautiful lightweight fan control application. It works flawlessly on my win11 M15R5

Except I am missing a save button to save my fan profile. After computer restart the modified curve becomes y=x.

A save button would be great.

**Comment by T-Troll** [comment]
It's designed as minimalistic, you can use `alienfx-gui` for more possibilities - like fan profiles.
Settings should save automatically.

> After computer restart the modified curve becomes y=x.

This is a bug. I'll fix it into next release.

**Comment by NoxaNM15R5** [comment]
Works well now, thank you.
