### ISSUE TITLE
Wasn't sure what form to inquire on for this but i had a question regarding the software you're using 

### ISSUE THREAD

**Issue by btunnell101** [T-Troll/alienfx-tools#223]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**System (please complete the following information):**
 - Model: [e.g. AlienWare m15R3]
 - Model details: [e.g. per-key rgb keyboard]
 - OS: [e.g. Windows 11 stable]

**Additional context**

Hello Good afternoon! 
My name is Brandon i have an Alienware 15r3 with some type of issue where my lights aren't detected. 
I would assume it's completely nonworking but sometimes randomly the lights will cut on. 
What i've landed on is that my AlienFX features some work and some do not but the way that programming works is if one partition
is damaged or having issues it won't run the thing at all. 
So what i'm curious about is that is there a way for me to disable the partitions that don't respond or work and manage to at least 
Have what's functioning to work for myself. 
That's why i found your 3rd party AWCC programming. 
It doesn't appear to be able to detect my device but every now and again when i boot my laptop up it just happens to detect the device. 
If you have any insight or help on this that would be amazing. 
Thank you so much!

**Comment by T-Troll** [comment]
1. First, check `alienfx-cli probe`. It should reveal all detected light devices. If your gear is m15R3, it should be 2 devices (APIv4 and APIv5), if M15r3 - only one (APIv2 or v3). Press "N" to "detect lights" question.
2. In case device(s) found - it can be controlled by all of my tools, so issue is inside AWCC.
3. In case no device found - this means Windows does not detect chip(s) - they connected to internal USB port. Check among "Unknown devices" or it can be light board (you have it AFAIR) fault.

PS: Next time please use "Discussions", not "Issues" for the questions.
