### ISSUE TITLE
Site reported as unsafe

### ISSUE THREAD

**Issue by middleagedman** [T-Troll/alienfx-tools#224]
FYI.. Microsoft smartscreen is now reporting https://github.com/T-Troll/ as unsafe for some reason.  Thought you should know.
![image](https://user-images.githubusercontent.com/13633609/197315030-2b070ee5-27e7-45ba-a627-b8f103b50cc0.png)

**Comment by T-Troll** [comment]
Read this - https://github.com/T-Troll/alienfx-tools/wiki/Why-antivirus-complain-about-some-alienfx-tools-components%3F
