### ISSUE TITLE
Fans spin at full speed after gui app is closed (or during shutdown/restart)

### ISSUE THREAD

**Issue by serge-bshkrv** [T-Troll/alienfx-tools#228]
**Describe the bug**
After exiting from the app, or restarting windows the fans start to spin at max speed and won't stop until the app is open again.

**To Reproduce**
1. Open alienfx-gui
2. Press Exit 
Fans spin at max speed, even after restarting. The only way to slow them down is to open alienfx-gui or awcc.

**Expected behavior**
Fan settings are preserved

**System (please complete the following information):**
 - Model: m15 r7
 - Model details: amd
 - OS: win 11

**Comment by T-Troll** [comment]
It can be normal - app just restore original power mode after quit, so in case it was "Performance" - fans will spin.
Anyway, i fix one close issue in 7.4.4 (g-mode not switched correctly in some cases), so check.

PS: You can always run `alienfan-cli setpower=N` to switch current system power mode.
