### ISSUE TITLE
M15R7 - Nvme temperature sensors locked at 60 degrees

### ISSUE THREAD

**Issue by luiz-fernandoalves** [T-Troll/alienfx-tools#234]
Describe the bug
SSD sensors are always showing 60 degrees.

To Reproduce

Open alienfx-monitor or alienfx-control and check values, they're different from samsung magician values for example. 

Expected behavior
SSD sensors must show the nvme drive temperatures. 

System (please complete the following information):

Model: Intel Core i7 M15R7
OS: win 11 - Build 22621.755 -  Experience Pack 1000.22636.1000.0
Core Isolation - Memory Integrity:  Enabled
AWCC: Not installed 
SSD Models: 2x Samsung 980 Pro 2TB

![Untitled](https://user-images.githubusercontent.com/40299326/200294640-88266915-4f33-4dab-a26a-0c49c697fd22.png)

**Comment by T-Troll** [comment]
Most probably it's not a bug - some SSDs have a fake temperature sensor, it's always return constant value into SMART (where i get it for GUI).

So check your SSDs SMART readings first.

Also, you should have MB SSD sensor as well - it's one of ESIF. Can't say exactly until take a look into BIOS dump (Dell name it, but Intel don't expose names).

**Comment by luiz-fernandoalves** [comment]
The only information about my motherboard, from HWiNFO :
Alienware 0TJXCY
Chipset: Intel Alder Lake-P PCH

From SMART: 
![image](https://user-images.githubusercontent.com/40299326/200441167-b8bf198d-24b5-470a-8267-be681eb66c7d.png)


From HWiNFO :
![image](https://user-images.githubusercontent.com/40299326/200441024-25b0ecfa-c399-4c50-af7a-a2514cc6dc07.png)


Actual readings from fx-control
![image](https://user-images.githubusercontent.com/40299326/200439761-b0c77e27-877c-413f-a840-88c4c775a7d4.png)

**Comment by T-Troll** [comment]
I see. But it locked into WMI to fake value.
What NVMe driver you are using? Windows default? Samsung?

**Comment by luiz-fernandoalves** [comment]
I've used Intel RAID drivers at windows install. Then, windows defaults.

**Comment by luiz-fernandoalves** [comment]
I've used Intel RAID drivers at windows install. Then, windows defaults.

**Comment by T-Troll** [comment]
So, you have it at RAID0?

**Comment by luiz-fernandoalves** [comment]
Nop. I've used this default option, but there's no RAID 0 setup:

![Bios1](https://user-images.githubusercontent.com/40299326/200503878-1aec71d7-87ae-4785-ba94-4ef74d0d43fa.jpg)

**Comment by luiz-fernandoalves** [comment]
Hey bro ..... I've changed the BIOS option to NVME and now the sensors are working fine.

![image](https://user-images.githubusercontent.com/40299326/201489645-3bd59e54-e22a-4ece-b8d3-ab788407a02b.png)

**Comment by T-Troll** [comment]
Aha, so RAID drivers report fake.
In case you're interested, i take this values from WMI (entry `ROOT\\Microsoft\\Windows\\Storage\\Providers_v2\\MSFT_PhysicalDiskToStorageReliabilityCounter`), which is, seems like filled not by system, but by storage driver.

Anyway, thanks for this bug. i'll add it into readme!
