### ISSUE TITLE
Does alienfan need to be always open in the background?

### ISSUE THREAD

**Issue by ash-hashtag** [T-Troll/alienfx-tools#237]
**Describe the bug**
Doesn't seem to work, when closed, or is it just my pc problem? Does it generally work when the app is closed?

**To Reproduce**
Open alienfan-gui, set curves, close the app, do some test, like open a game, the fans won't start till I open the alienfan again

**Expected behavior**
should automatically fans spin according to temps in background

**Screenshots**
You gotta feel the heat

**System (please complete the following information):**
 - Model: Dell g15 5515
 - OS: Windows 11 stable

**Comment by T-Troll** [comment]
Yes, fan control is only active then app running.
System state stored at app start and restored at quit.

There is no other way for manual fan control, AWCC using the same, they just close UI, but not the app.
