### ISSUE TITLE
I Just Lost My Manual Fan Curve :-(

### ISSUE THREAD

**Issue by TheSQLGuru** [T-Troll/alienfx-tools#242]
I had created very particular fan curves. I was on GPU Internal Thermistor and clicked the checkbox for Fan 3, and the fan curve grid went blank. When I clicked Fan 3 checkbox again, my custom fan curve was gone. Not good!! You absolutely must keep the fan curve somewhere, permanently unless manually deleted, and restore it when the appropriate checkbox is reeneabled.

**Comment by T-Troll** [comment]
Work as designed right now, unchecking fan remove curve.
In the next release, i change this behavior, as well as many others.
