### ISSUE TITLE
"Lights" tab not clickable on G15 5515

### ISSUE THREAD

**Issue by 09s23jf038** [T-Troll/alienfx-tools#248]
**Describe the bug**
"Lights" tab are not clickable on G15 5515. I can click on Settings, Profiles and Fan and Power fine though. Tried latest and a 10 day ago build but both got the same problem for me.

**System (please complete the following information):**
 - Model: G15 5515
 - Model details: rgb keyboard (not zoned, i think)
 - OS: Windows 10 Home Single

**Comment by T-Troll** [comment]
This means any light device not found into the system.
You should also have a notification about this fact.

It's normal for G-series - only Alienware keyboard supported. Yours are not even RGB, red only, and have no interface for control.
