### ISSUE TITLE
AlienFX not displaying Detected Devices

### ISSUE THREAD

**Issue by JazzyJazzjazzy** [T-Troll/alienfx-tools#278]
Good day,

Installed V 7.10.6.1 and used CLEAR DEVICE option. Grid cleared. Selected DETECT DEVICE and placed check mark in appropriate box. Interface remained BLANK and white and did not populate.

Receive message: WARNING, CHECK LIGHTS.

**Comment by T-Troll** [comment]
Seems like damaged devices.csv file. Let me check, you can use older file (from 7.10.1) for now.

**Comment by T-Troll** [comment]
Yes. It was this. I update release, re-download and check now.

**Comment by JazzyJazzjazzy** [comment]
Hello my friend, it works GREAT, now. Thank you.

**Comment by neoacevedo** [comment]
Uhm... I try to uncompress the zip file and I get an error with the file Mappings/devices.csv. Maybe related to this issue?

**Comment by T-Troll** [comment]
No. Seems like damaged .zip
