### ISSUE TITLE
Base Fan Speed off of Add-in Nvidia PCI-E GPU Temp

### ISSUE THREAD

**Issue by Joshaze** [T-Troll/alienfx-tools#284]
**Is your feature request related to a problem? Please describe.**
I wish that I could ramp up the system fans in response to an increase in an add-in GPU's temperature rather than just the iGPU. 

**Describe the solution you'd like**
I would like to be able to create a fan response curve based on an add-in Nvidia GPU's temperature.

**Describe alternatives you've considered**
N/A

**System (please complete the following information):**
 - Model: AlienWare Aurora R8 Desktop
 - OS: Windows 10 stable

**Additional context**

**Comment by T-Troll** [comment]
This depends on the sensor(s) you are used to controlling the fan.
Usually, First GPU sensor is about dGPU (as well as some other). ESIF GPU sensor (it's named "CPU participant (GFX)") is about iGPU.
So choose correct sensor(s).
