### ISSUE TITLE
Trying to Collect Data for my X17 R1 Laptop

### ISSUE THREAD

**Issue by TheSQLGuru** [T-Troll/alienfx-tools#301]
Hey guy. Sorry for ghosting. Life has been . . . suboptimal.  :-( 
![USBPcap](https://user-images.githubusercontent.com/2779491/222403455-e1e0879f-20ef-4f42-bc30-0945936cb604.jpg)
![HID and Keyboards](https://user-images.githubusercontent.com/2779491/222403462-c5d52d7a-6f5e-4d03-9ab1-71cba20d6b0a.jpg)
![touchpad 2](https://user-images.githubusercontent.com/2779491/222403463-d22de024-7cdb-4b62-b4d7-f6ce98cf9eb1.jpg)
![touchpad 1](https://user-images.githubusercontent.com/2779491/222403464-7b24c155-e148-4244-abeb-e562bd2e7a5a.jpg)

I tried walking through your Wiki page on how to provide you the information needed to produce an exact match for my computer lighting, but I have many issues. 

1) I have multiple keyboards, and a butt ton of HID devices. How am I supposed to know which one of them is my laptop's physical keyboard? See attached pic.

2) I have a trackpad device shown in two images. One has the Properties open, and there is no PID. I am pretty confident that you don't want DELL/0A8F because that is on multiple components. What's the story?

3) Even more odd is that the trackpad is not "under" a USB anything when viewed by Connection. It shows up under the I2C HID Device, which subordinate to the Serial IO I2C Host Controller. And as you can see in the USBPcap pic, no I2C device shows up there to choose. 

4) In my Devices list, I don't see anything that looks like it might be my Power Button Light, the Lid Light or the Tron Light.

5) In USBPcap, how can I differentiate between the various items - as multiple have the exact same name (HID-compliant vendor-defined device for example, and USB Input Device)?

So it seems I need some more hand-holding. It also seems that someone should put some pictures in the Wiki page for this process to help folks like me. :-)

**Comment by T-Troll** [comment]
Well... I see all devices at #2 - 6/1 is internal devices, 9 is external keyboard.
Hint: look at "vendor-defined device".

Touchpad doesn't have a separate light device and served by common tron device with PID_0550 (or 551 for new gear).

**Comment by TheSQLGuru** [comment]
I have it just about figured out now!! It's been AGES since I had WireShark open! :-D I am about to do a dimming and brightening (something you didn't ask for) of the track pad, and then cycle through effects for the track pad. Then I can upload the files for you.

**Comment by T-Troll** [comment]
APIv4 it uses support per-light hardware brightness even in mine SDK. Just locate it's light ID.
Or you want to support other hardware?

**Comment by TheSQLGuru** [comment]
Sorry for leaving this hanging. I don't have this laptop any longer, so you can close the ticket.
