### ISSUE TITLE
Issues and Ideas : AZERTY Keyboard shortcuts | Dim with screen | Power modes

### ISSUE THREAD

**Issue by XenocFr** [T-Troll/alienfx-tools#305]
Hello !
Firstly :  thank you very much for developing an open source program like this one.
You're better than Dell, without making theirs computers x-)

I have a French Dell G7 7700 (buggy crap by the way) with Win11 and I've got some ideas and issues : 

- With an AZERTY keyboard, you write an '@' with alt gr+0 ('@' is on the '0' key) (alt gr is another alt key, instead of the right alt, because AZERTY is complex). So with shortcuts enabled, I'm switching to the manual profile instead of writing the character.
That's quite anoying because I like using the G button and keyboard light shortcut (F7 on this keyboard) but I can't if I disable shortcuts.
So please, can you add an option to only active G-key and keyboard light (or FXX keys in your code) ?
Or maybe adding customs shortcuts (but that means more work for something not really useful I think).

- Issue with G-key on the last update : disabling G mode with the G-key doesn't restore the previous mode but the manual mode.

- How can we know which level corresponds to Dell's profiles : optimized, cool, performance, quiet ?

- An idea for dimming : it would be great to dim the keyboard according to the screen brightness (at least on laptops).

I hope this message will help you improve the best (not)Dell tool ever made ^^.
Waiting for your response, have a nice day !

**Comment by T-Troll** [comment]
Bonjour!

1. Yes, this is an issue. I use ANY Alt as a keyboard shortcut, AltGr is RIGHT Alt. Let me think how to avoid it.
2. Aye. It's a price of simplification, now only manual mode can be set after g-mode off, so it's not a bug. Being honest, i don't think anyone will complain about it.
3. There is no way to get names, it's predefined list inside AWCC, and different from system to system. You can check power limits into HWINFO to get a hint which mode is which.
4. Nice idea, but require some effort. Now i don't mess with brightness, i only check on/off/dim state for monitor.

**Comment by T-Troll** [comment]
I fix 2 at latest release, please check.
But 1... There is no way to detect was it AltGR or Ctrl+Alt. Still need to check and think.

**Comment by XenocFr** [comment]
> I fix 2 at latest release, please check. But 1... There is no way to detect was it AltGR or Ctrl+Alt. Still need to check and think.

Hello, thank you for your reply and fixes.
I suggested in my first post to add an option to activate/detect only the FXX keys (G-key included). Is this possible ? (may only require an if/else)

**Comment by T-Troll** [comment]
Well... 
I don't like it conceptually, trying to keep app as simple as possible. I have an option to disable shortcuts already, so new one is looks like something weird.

Let me think how to solve it the other way.

**Comment by T-Troll** [comment]
Check latest release - now i keep Fn always on and disable other sortcuts only.

**Comment by XenocFr** [comment]
My FN keys are only enabled when "keyboard shortcuts" are activated. So nothing changed in my case...

**Comment by T-Troll** [comment]
Yes, it was a small bug.
Try [this one](https://github.com/T-Troll/alienfx-tools/files/10973562/alienfx-gui.zip)

**Comment by XenocFr** [comment]
Yes it is working thank you very much !

**Comment by T-Troll** [comment]
The only issue remains is sync-screen dimming. Let me think about it a bit more, it's possible, but i don't sure useful for all.

**Comment by T-Troll** [comment]
There is no simple way to get the brightness change event. So this one postponed.
