### ISSUE TITLE
Switch between Lights has changed

### ISSUE THREAD

**Issue by MateusBMP** [T-Troll/alienfx-tools#307]
**Describe the bug**
Before, in some version, the dimming button on the keyboard switch between the max light, the dim light and the lights off. Now, only switch between dim and light off. I don't know if it is necessarily a bug.

**To Reproduce**
1. Open the Settings view into AlienFX Control
2. Switch between light powers with `fn + F7`

**Expected behavior**
Switch between three lights options is expected.

**System:**
 - Model: Alienware m15 R6
 - Model details: m15R6 Keyboard+Tron
 - OS: Windows 11 stable

**Additional context**
The command in this keyboard is `fn + F7`. The last effect, looking for Settings screen is:

1. "Turn on lights" disabled,
2. "Turn on lights" enabled and "Dim lights to" disabled
3. "Turn on lights" enabled and "Dim lights to" enabled

**Comment by T-Troll** [comment]
Definitely a bug, it should work like before.
I modify this in last release, seems like some bug comes. Ok, let me check and fix.

> "Turn on lights" disabled,
> "Turn on lights" enabled and "Dim lights to" disabled
> "Turn on lights" enabled and "Dim lights to" enabled

So what operation above works incorrectly? Also, what do you have into "Keep power..."/"Dim power..."?

**Comment by T-Troll** [comment]
UPD: Yes, i confirm. AlienFX button (Fn+F12 on my gear) work incorrectly.

**Comment by MateusBMP** [comment]
> Here are the fix: [alienfx-gui.zip](https://github.com/T-Troll/alienfx-tools/files/10934251/alienfx-gui.zip)

Now it's right!

> In case of lights dimmed by 2 and 3 point, it will switch between off/dimmed only, blocking full brightness. It's not a bug.

Now I understand, thank you for the explanation ;)
