### ISSUE TITLE
AlienFan Pop Up Is Distorted

### ISSUE THREAD

**Issue by JazzyJazzjazzy** [T-Troll/alienfx-tools#309]
AlienFan Pop Up Is Distorted and not showing values/numbers as it should.
Ver 8.2.1.2
![AlienFan Distortion](https://user-images.githubusercontent.com/40358464/224613689-de7cddc6-e4bc-4b50-8ddd-5fdc666f083e.png)

**Comment by T-Troll** [comment]
Oh, i see. Will be fixed in next release.

**Comment by T-Troll** [comment]
Should be fixed in [#8.2.2](https://github.com/T-Troll/alienfx-tools/releases/tag/8.2.2).
