### ISSUE TITLE
AlienFx Crashes to Desktop

### ISSUE THREAD

**Issue by JazzyJazzjazzy** [T-Troll/alienfx-tools#311]
AlienFx Crashes to Desktop when on COLORS page, Add ZONE, SELECT FROM LIST. After selecting keys and then hit APPLY, crash occurs.

**Comment by T-Troll** [comment]
Confirm. Looks really strange, WHERE it really happened. Will fix ASAP.

**Comment by T-Troll** [comment]
Fixed - re-download last release.

**Comment by JazzyJazzjazzy** [comment]
Works Great, sir. Thank you.
