### ISSUE TITLE
AlienFan persistently drops out of monitoring phase.

### ISSUE THREAD

**Issue by JazzyJazzjazzy** [T-Troll/alienfx-tools#317]
AlienFan persistently drops out of monitoring phase and CPU and GPU overheat. RPM values remain at 500 and do not change,

This has been the case on initial startup and resume from sleep. Changing the profile from MANUAL to anything else and back to MANUAL usually resolves issue but it returns.

Also, noted that POWER MODEs are now numbers, ie "Level 163". Is this by design? Thank you.

**Comment by T-Troll** [comment]
Thanks, it's serious.

You are not the first to report me about stuck fans, seems like latest BIOS make this shit.
Can you remind me your systemID (visible in fan cli)?

> Also, noted that POWER MODEs are now numbers, ie "Level 163". Is this by design? Thank you.

Ah, yes. Power mode name now have not the number, but real hardware power mode ID (internal change). It can be from A0 to AB hex, A0 balanced, usually, AB is G-Mode/Performance.

**Comment by T-Troll** [comment]
Check latest release. Did it fix this issue?

**Comment by JazzyJazzjazzy** [comment]
Latest release appears to have fixed this issue. Will post back if anything else noted, Thank you.

**Comment by JazzyJazzjazzy** [comment]
Spoke too soon, issue still persists in latest HOTFIX,

**Comment by T-Troll** [comment]
So it's random. Ok, tell me your SystemID, please...

**Comment by JazzyJazzjazzy** [comment]
I remember now. I also remember that I had no Device ID. You thought that strange  at the time.

C:\Program Files\AlienFX Tools>alienfan-cli
AlienFan-CLI v8.2.5
Supported hardware (0) detected, 2 fans, 11 sensors, 6 power states.
Usage: alienfan-cli command[=value{,value}] {command...}

**Comment by JazzyJazzjazzy** [comment]
C:\Program Files\AlienFX Tools>alienfan-cli getpower
AlienFan-CLI v8.2.5
Supported hardware (0) detected, 2 fans, 11 sensors, 6 power states.
Power mode: Manual (0)

C:\Program Files\AlienFX Tools>alienfan-cli setpower=1
AlienFan-CLI v8.2.5
Supported hardware (0) detected, 2 fans, 11 sensors, 6 power states.
Power mode set to Level 1 (163)

C:\Program Files\AlienFX Tools>alienfan-cli getpower
AlienFan-CLI v8.2.5
Supported hardware (0) detected, 2 fans, 11 sensors, 6 power states.
Power mode: Manual (0)

C:\Program Files\AlienFX Tools>alienfan-cli getpower
AlienFan-CLI v8.2.5
Supported hardware (0) detected, 2 fans, 11 sensors, 6 power states.
Power mode: Level 1 (163)

C:\Program Files\AlienFX Tools>alienfan-cli setpower=1
AlienFan-CLI v8.2.5
Supported hardware (0) detected, 2 fans, 11 sensors, 6 power states.
Power mode set to Level 1 (163)

**Comment by JazzyJazzjazzy** [comment]
Last item is after resume from sleep.

**Comment by T-Troll** [comment]
> Power mode: Level 1 (163)

If last 2 after resume, this means you are in Balanced mode, which is not reset to manual!
Interesting...

**Comment by JazzyJazzjazzy** [comment]
just confirming that last two are after resume.

**Comment by T-Troll** [comment]
Ok, Wonder how it happened.
Please remind me you model.

**Comment by JazzyJazzjazzy** [comment]
> Ok, Wonder how it happened. Please remind me you model.

Alienware m17 R4

**Comment by JazzyJazzjazzy** [comment]
Update: Sir, AlienFan is properly working at start up and resume from sleep. Thank you for your extra efforts. Peace.

**Comment by T-Troll** [comment]
At least. Great.
