### ISSUE TITLE
AlienFX not displaying Detected Devices

### ISSUE THREAD

**Issue by JazzyJazzjazzy** [T-Troll/alienfx-tools#332]
Program working so  well that I have had no need to do anything but "Start With Windows" and so never noticed issue until now.
Ver 8.2.6.2 has "blank" Detected Devices window. Probably damaged devices.csv as before. Thank you.

**Comment by T-Troll** [comment]
I check at mine system, it's ok.
This can happen by these reasons:
- You devices really not listed or not detected (do you have something into "Device:" list?)
- devices.csv damaged
- devices.csv have some bug into your system block. Remind me the model, please!

**Comment by JazzyJazzjazzy** [comment]
Reinstalled from new release. All good. Thank you.
