### ISSUE TITLE
Sensors Not Correctly Dispalyed

### ISSUE THREAD

**Issue by JazzyJazzjazzy** [T-Troll/alienfx-tools#337]
My listed Sensors in AlienFx-Fan does not correspond to what is in my registry. Registry Entries are below and .png shows what is displayed in AlienFx-Fan.

"SensorName-0-0"="ESIF sensor 1"
"SensorName-0-1"="ESIF sensor 2"
"SensorName-0-2"="ESIF sensor 3"
"SensorName-0-3"="ESIF sensor 4"
"SensorName-0-4"="ESIF sensor 5"
"SensorName-0-5"="ESIF sensor 6"
"SensorName-0-6"="ESIF sensor 7"
"SensorName-1-1"="CPU Internal Thermistor"
"SensorName-1-6"="GPU Internal Thermistor"
"SensorName-2-0"="SSD sensor 1"
"SensorName-2-1"="SSD sensor 2"
![Display](https://user-images.githubusercontent.com/40358464/232252614-e72a2279-452e-4473-98cb-7ca308799966.png)

**Comment by T-Troll** [comment]
This means you lost ESIF sensors, but it was into the system before.
ESIF sensor data provided by Intel DPTF (Dynamic Tuning Framework driver), so make sure you have it installed.
Also, some DPTF drivers do not provide this data to system (just collect and use inside the driver), so better check you have drivers from Dell's support site, not from Intel one (or just find one which provide it).

How to check you have DPTF data? Open `perfmon`, select "Performance monitor", press "+" button. Then the list populated, look for "ESIFDeviceInformation" entry. In case it presents into the list, all work correctly.

**Comment by JazzyJazzjazzy** [comment]
Hello,

In PERFMONITOR, I do not have ESIF Entry. Goes from Energy Meter to Event Log, skipping ESIF. 

I reinstalled Intel-Dynamic-Tuning-Intel-Dynamic-Tuning-Driver_90GWR_WIN64_8.7.10600.20700_A12.EXE from DELL site and observed No Change in my display.

Also used [alienfx-tools.msi] to reinstall AlienFx as opposed to the .zip and still No Change.

**Comment by T-Troll** [comment]
As i said, some DPTF does not support it.
You can try `fan_sdk_v1,zip` version (READ README FIRST!), but i don't sure it supports fan control at your system.

**Comment by JazzyJazzjazzy** [comment]
Your program has been supporting my laptop since I started using it months ago. Now, why suddenly it just stops supporting it? 
It is a relatively new Alienware m17 R4 with i7-10870H, RTX 3070.

**Comment by T-Troll** [comment]
V1 is older SDK and some models not supported. But AFAIR R4 is.

**Comment by JazzyJazzjazzy** [comment]
Why would I have to resort to using V1 when laptop previously running fine on most up to date version? What has changed?

**Comment by T-Troll** [comment]
Good:
- You will have more sensors
- Lower CPU usage for fan control
Bad:
- Antivirus will be crazy about it

BTW, i check [this](https://github.com/T-Troll/alienfx-tools/wiki/Supported-and-tested-devices-list) - yes, R4 is supported.

**Comment by JazzyJazzjazzy** [comment]
Thank you for this information but I think I will pass. When you UPDATE your software is when I notice inconsistencies creep in or things get broken. Kindly recall most of my previous issues were observed after an update. This current issue just "popped up" out of now where after my computer has been fine for many months. I do not think a 10th Generation cpu is that old to need V1 SDK. Once. I suggested separate versions in order to avoid this, however, you wrote that you  wish to maintain commonality and I understand and respect that. I will download previous versions to see if any one of them still work. If not, then I will continue using current version as my fans do reliably respond to the visible sensors. Thank you.

**Comment by JazzyJazzjazzy** [comment]
Sir, I wanted you to see my CPU & GPU Temps while running MSFS 2020 in a 29 degree Celsius room. I could not have achieved these values without your software as I have played this game for the past year and I know what temps have been. I am grateful for all of your work. Thank you. Maybe if I can find the V1 SDK, I will give it a try.

![CPI   GPU Temps](https://user-images.githubusercontent.com/40358464/232339869-c6046ab4-f702-414c-96a9-a9601891c62a.png)

**Comment by JazzyJazzjazzy** [comment]
![Sensors](https://user-images.githubusercontent.com/40358464/234577803-1a7ff7ee-448d-44ff-80f6-6e35cce08c13.png)
Repair installed W11 and now all sensors are visible. I suspect that it was my W11 install and not your software causing issues. Apologies. Thank you.
