### ISSUE TITLE
Scorchout interfere with writing

### ISSUE THREAD

**Issue by XRone99** [T-Troll/alienfx-tools#338]
I've noticed that if you use international keyboard the scorchout for fan control "ALT+5" makes impossible to type the symbol "€".
I get that maybe it's not a big problem for most users but here in Europe it turns out to be pretty annoying.

May I suggest to make these fan control scorchouts optional or customazible.
(for example I have a Alienware X17 R2 and since I use AlienFX Tools the Fn+F2 to Fn+F6 combination has become useless since without command centre it's impossible to set Macros, maybe it would be a good replacement to make those combinations default)

**Comment by T-Troll** [comment]
You can disable it in settings.
Unfortunately, the local keyboard uses international shortcuts quite frequently.
