### ISSUE TITLE
Lights tab randomly disappears - Dell G15 Ryzen 5515

### ISSUE THREAD

**Issue by mathprnb** [T-Troll/alienfx-tools#342]
**Describe the bug**
I've managed to turn on the lights for a while on version 8.2.6.6, tried hibernating and restarting and it was OK. I got it to work again after uninstalling AWCC and AlienFX, and then installing both again. However after a few hours the keyboard lights were off again, and the tool doesn't seem to recognize it anymore. The same thing happened on the previous version.  On AWCC it says it could not detect a AlienFX device.

**To Reproduce**
1. On a Dell G15 Ryzen install AlienFX and configure the keyboard lights.
2. After a few restarts it will stop showing up.

**Expected behavior**
The lights tab was expected to always show up and the keyboards lights detected.

**Screenshots**
![image](https://user-images.githubusercontent.com/49698130/236063958-3728e656-81b0-4705-a1c8-7dbc42eefbbb.png)

**System (please complete the following information):**
 - Model: DELL G15 5515 - Ryzen Edition
 - OS: Windows 11 stable

**Additional context**
I genuinely thank you for developing this application, since I just don't have any hope on DELL fixing their tool, I had already given up on trying to get it to work. If any further information is needed, I'd be glad to help.

**Comment by T-Troll** [comment]
Lights dab can be disabled in case no light devices detected into the system.
So BOTH AWCC and my tool can't find USB HID device presenting light control.

I have bad news for you.... Seems like your system dying into this, maybe cable not fit well now, so it's a hardware issue.
The only hope it's BIOS issue - did you update it recently (f.e. from Windows Update)? If yes, roll back immediately and disable automatic BIOS updates!

Unfortunately, i can't do anything in this case - i can't control a device not present into the system. As well as AWCC.
