### ISSUE TITLE
alienfx-cli can not control m18r1 keyboard lights

### ISSUE THREAD

**Issue by yuhao71** [T-Troll/alienfx-tools#348]
I install the 8.2.7 version msi files,but when I defined some key lights and save it ,it can not effcetive in my new m18r1 keyboards
![QQ截图20230527210343](https://github.com/T-Troll/alienfx-tools/assets/7792378/3d77324e-d1a3-42fc-bbe1-777200c2a0b6)
![QQ截图20230527210357](https://github.com/T-Troll/alienfx-tools/assets/7792378/dcc059a0-3c55-46fa-a8ee-564bf0c8fa26)
![QQ截图20230527210404](https://github.com/T-Troll/alienfx-tools/assets/7792378/b400ad19-6cdb-499f-89af-e74d83907205)

**Comment by yuhao71** [comment]
![image](https://github.com/T-Troll/alienfx-tools/assets/7792378/a53cb45e-f7b8-4d1a-9b33-c36172dbe947)

**Comment by T-Troll** [comment]
1. Breath require 2 colors and some timing (sliders).
2. Anyway, it didn't supported for APIv5 hardware, but you can emulate it via Grid effects.
3. But most interesting fact, you have 0 lights defined for keyboard device! I didn't configure out how it is possible yet.

So, can you, please:
- Open CMD into app folder
- Run `alienfx-config backup`
- Share 4 .reg files it generates here

**Comment by yuhao71** [comment]
OK,I am out for work for a few days,I will upload in 2023.06.01

**Comment by yuhao71** [comment]
hao can i transfer the reg files to you?

**Comment by T-Troll** [comment]
Pack in .zip and attack here.
