### ISSUE TITLE
No CLI's work.

### ISSUE THREAD

**Issue by davies-w** [T-Troll/alienfx-tools#364]
**Describe the bug**
I've tried running as administrator, normal etc. Powershell, normal shell, just clicking on CLI.  Nothing works, it just brings up a dialog saying "you want to run this", and then it becomes grey screen and then just exits. Nothing works. I've tried alienfan-cli maxrpm, nothing.

**To Reproduce**

**Expected behavior**
I'd expect to see some text in my shell window

**Screenshots**

**System (please complete the following information):**
 - Model: Alienware Laptop m15 r2
 - Model details: stock
 - OS: Windows 10 latest patch

**Additional context**

**Comment by T-Troll** [comment]
It requires Administrator CMD.
If you don't have it will ask for elevation (prompt) then open NEW CMD which will be closed immediately after app finish.

So open Administrator CMD, navigate to the tools folder, run from it.

**Comment by davies-w** [comment]
That works!!! Thank you so much!!
