### ISSUE TITLE
Deleting AlienFX configuration

### ISSUE THREAD

**Issue by DinnerBug** [T-Troll/alienfx-tools#372]
This is not a bug, just a request for help.
I would like to delete previous AlienFX's settings and start fresh, It's something I like to do from time to time. However uninstalling the software doesn't delete the config, there is no option to delete configs in the uninstaller and I couldn't find anything in the software itself.

**Comment by T-Troll** [comment]
There is an option - just read project readme!
Use `alienfx-config` script - it can back up, restore or DELETE all options!

**Comment by DinnerBug** [comment]
Thanks
