### ISSUE TITLE
Libre Hardware Monitor sensors not showing anymore after update

### ISSUE THREAD

**Issue by DinnerBug** [T-Troll/alienfx-tools#373]
**Describe the bug**
Launching Libre Hardware Monitor before AlienFX-GUI does not result in the program showing as many sensors as before upgrading to the latest version. I'm particularly interested in the GPU core and the CPU core temperatures. Launching Libre Hardware Monitor causes some sensors to appear but not all and not the ones I need. The issue could have also been caused by the latest Windows update(?)

**Screenshots**
![Screenshot 2023-08-22 200723](https://github.com/T-Troll/alienfx-tools/assets/75734620/811bf1df-5699-41bb-b185-01982f43712a)

**System:**
 - Model: Alienware Aurora R8
 - Model details: [e.g. per-key rgb keyboard]
 - OS: Windows 10 Home
 
 Thanks

**Comment by DinnerBug** [comment]
after updating to the latest version, the issue persists

**Comment by T-Troll** [comment]
Oh, i found the source.
Libre now delivers a lot of sensors, but i only take first 32. Now i increase the limit to 256. ^_^

Check this version - [alienfx-gui.zip](https://github.com/T-Troll/alienfx-tools/files/12558990/alienfx-gui.zip)

I change the method i count it into next release.
