### ISSUE TITLE
Aurora R7

### ISSUE THREAD

**Issue by Reshuffling** [T-Troll/alienfx-tools#378]
I feel like I've tried everything now but I can't get the FanControl to work at all. Tried both GUI and CLI, with the [8.5.0](https://github.com/T-Troll/alienfx-tools/releases/tag/8.5.0) + SDKv1 and Registry Update. It finds the fans and three sensors, it doesn't seem to save my settings after input through the CLI. 

![image](https://github.com/T-Troll/alienfx-tools/assets/3051951/e951310d-167d-49db-bec5-5e5442c9f961)
![image](https://github.com/T-Troll/alienfx-tools/assets/3051951/838ceef8-7d6c-4e23-9a71-7d32f6eeb230)

![image](https://github.com/T-Troll/alienfx-tools/assets/3051951/da30a929-6051-4642-b49f-20b7e0e51d62)
![image](https://github.com/T-Troll/alienfx-tools/assets/3051951/a0a8d38a-cded-4345-862f-4298e9a8591b)
![image](https://github.com/T-Troll/alienfx-tools/assets/3051951/f2c2640e-f29a-4633-b4fe-34c8f1c505e1)

![image](https://github.com/T-Troll/alienfx-tools/assets/3051951/d5d3c868-b6e0-45f8-afca-ce5ff4c0dc59)

Windows 10 1709.

**Comment by T-Troll** [comment]
Fan control only available into Manual mode. Add `unlock` or `setpower=0` before fan operation.

**Comment by Reshuffling** [comment]
![image](https://github.com/T-Troll/alienfx-tools/assets/3051951/cca6e05d-98fd-4d06-9c3c-b858dd7927d0)

**Comment by T-Troll** [comment]
No. Into ONE command line - `unlock setfans=100,100,100`
In case getfans still show "-1" after this - this is an issue to examine.

**Comment by Reshuffling** [comment]
![image](https://github.com/T-Troll/alienfx-tools/assets/3051951/346f8dbc-9b2d-4c28-bb0f-851e6e0ad46e)

**Comment by T-Troll** [comment]
Check some services - it can stay even after GUI closed.
According to readings, some interfere and even switch power mode back to auto.

**Comment by T-Troll** [comment]
Try to use `alienfan-gui` - it can block this, in case it works - look who switch modes.

**Comment by Reshuffling** [comment]
![image](https://github.com/T-Troll/alienfx-tools/assets/3051951/db4093e1-ca14-4db5-a2d3-de49b786799e)

Fan 3 boost randomly too 400-600 RPM and then just dies to 0 for several seconds. 

Have uninstalled FanControl and will reboot.

**Comment by Reshuffling** [comment]
![image](https://github.com/T-Troll/alienfx-tools/assets/3051951/8f60776b-9d37-4b78-b395-6e104b723fd6)
Nope, nothing seems to happen.

**Comment by T-Troll** [comment]
Aha. Control doesn't work.
Let me think a bit and check the code.

You are at v1, right?

**Comment by Reshuffling** [comment]
> You are at v1, right?
fan-SDK_V1 yes.

**Comment by T-Troll** [comment]
I got the point.
R7 has 2 power modes only, and no manual one.
I use the same control (not SDK!) code for both V1 and V2, so it's always report mode as uncontrolled (that's why you don't have red dot on curve).
I'll fix this into the next version.

**Comment by Reshuffling** [comment]
Yeah, setpower=2 seems to work.
![image](https://github.com/T-Troll/alienfx-tools/assets/3051951/4022c1c6-eff5-4dda-9577-e0ea339b3939)

**Comment by T-Troll** [comment]
Did you check latest version? I make some changes into v1 SDK for your system.

**Comment by Reshuffling** [comment]
I just use the latest version, not using the v1 at all with this command:
alienfan-cli unlock setpower=2 setfans=100,100,100 and it works.

**Comment by T-Troll** [comment]
Well....

- V1 needed to control your lights (V2 support it, but doesn't work after all tests).
- Your BIOS did not report current boost (always -1 = error). So current GUI will not work correctly so far.
- You don't need to issue "unlock" into V2 - there is no manual mode (mode 0) at your system. Into V1, i emulate it.

So... In case you only need fan CLI, you can use this. In case you need fan GUI or lights, we need to go a bit deeper and tune it for your system more (v1 or v2).

**Comment by Reshuffling** [comment]
I am up to get this solved once for all if you have the time and energy. Let me know what you need.

**Comment by T-Troll** [comment]
I can add a patch to fan control GUI (but it can affect other systems), but lights is not solved for v2 (BIOS can not accept data correctly, seems like WMI method have an error in description).

**Comment by Reshuffling** [comment]
Well R7 are fun machines, I will just go with the V2 CLI command. Lights are what they are. At least the fans work with the CLI. Marking this as closed.
