### ISSUE TITLE
Is i9-13900HX Supported Yet?

### ISSUE THREAD

**Issue by JazzyJazzjazzy** [T-Troll/alienfx-tools#391]
Hello,

I downloaded the latest version and it shows TWO CPUs in the window and only one curve.

Have you written in support for the i9-13900HX yet? Thank you. 

I have new Alienware M18 R1 laptop. Does AlienFx support this keyboard?

**Comment by T-Troll** [comment]
1. Share a screenshot, please. Tool is not depend on CPU type, Alienware platform only.
2. Yes, m18R1 supported. But automatic profile is not into database yes, use manual setup.

**Comment by JazzyJazzjazzy** [comment]
Apologies for late reply. I suspect  that I only have two CPUs listed because I did not install your files from the DPTF folder. No problem.

I have Alienware 18 with Cherry Dark Keyboard. I attempted to set up my lights but I am not meeting with success. Kindly have a look at my photos.

Nothing happens on the keyboard lights. Am I missing something? AWCC is completely uninstalled. Thank you.




<img width="1065" alt="Screenshot 2023-12-18 135907" src="https://github.com/T-Troll/alienfx-tools/assets/40358464/accbd397-c93c-4cab-ac72-1b6d670a038e">
<img width="949" alt="Screenshot 2023-12-18 135500" src="https://github.com/T-Troll/alienfx-tools/assets/40358464/715edb0c-161b-4355-9785-7e47a180d8ae">
![Screenshot 2023-12-18 135718](https://github.com/T-Troll/alienfx-tools/assets/40358464/ae40d8d6-39a4-4ac5-a292-424de2944bf8)

**Comment by JazzyJazzjazzy** [comment]
![1](https://github.com/T-Troll/alienfx-tools/assets/40358464/dc8b41fb-174e-4c79-97af-d7fb538296db)

**Comment by JazzyJazzjazzy** [comment]
Also noted that G-Mode Key lights up when depressed. It has no effect, though. The Fan Curve in ALienFan manages the fans. The boost from the Power Profile changing to TURBO does not occur since AWCC is not installed. Basically, only the KEY illuminates. Thoughts?

https://www.dell.com/support/manuals/en-us/alienware-command-center/awcc_ug_6.x/performance-page-g-key-mode-in-system-and-game-mode-for-dell-g-series-computers?guid=guid-f26f92fa-6f76-4e72-b6c6-ac9055d77a1e&lang=en-us#:~:text=Table%20of%20Contents-,Performance%20page%20G%2Dkey%20mode%20in%20system%20and%20game%20mode,activate%20the%20G%2Dkey%20mode.&text=Once%20the%20G%2D%20key%20is,and%20a%20notification%20is%20displayed.

**Comment by T-Troll** [comment]
No, you have 4 fans, not 2! 2 for CPU, 2 for GPU and can control all of them.

About keyboard lights - at some devices (f.e. 410k/510k) one key can have 2 IDs - one for on, one for off (f.e. for CapsLock etc).
So check more IDs than it's off - it can be this.

**Comment by JazzyJazzjazzy** [comment]
> No, you have 4 fans, not 2! 2 for CPU, 2 for GPU and can control all of them.
> 

Understood, four fans total.

> About keyboard lights - at some devices (f.e. 410k/510k) one key can have 2 IDs - one for on, one for off (f.e. for CapsLock etc). So check more IDs than it's off - it can be this.
> 

How to check IDs?

> And yes, you don't have DPTF (ESIF) working correctly, seems like your DPTF driver doesn't support it. Or maybe Intel renames the sensor block, and we need to locate the new one.

How to locate the name?

**Comment by JazzyJazzjazzy** [comment]
In AlienFan, when I select CPU 1 on the Left side, highlight GPU on the Right side, the Modified Curve is displayed.

BUT, when I select GPU on the Left side and highlight CPU on the Right side, an Unmodified CPU Curve is displayed? 

<img width="468" alt="Screenshot 2023-12-2 065855" src="https://gith
<img width="461" alt="Screenshot 2023-12-21 065544" src="https://github.com/T-Troll/alienfx-tools/assets/40358464/d362da6d-2ee0-4765-acd9-ad50c6378a8e">
ub.com/T-Troll/alienfx-tools/assets/40358464/4ae97652-b448-47dc-bc2f-a404e0bad318">

**Comment by T-Troll** [comment]
> BUT, when I select GPU on the Left side and highlight CPU on the Right side, an Unmodified CPU Curve is displayed?

Curves assigned per-fan, so yes, you can (and should) have different curves for every fan.

> Is it possible to display the Default Bios Fan Curve?

Yes, but useless. It's zero-zero.

**Comment by JazzyJazzjazzy** [comment]
Thank you, will do.
