### ISSUE TITLE
any chance to add x14 support?

### ISSUE THREAD

**Issue by dynamiszmx** [T-Troll/alienfx-tools#422]
No device detected on my x14 r2. It has a one tone rgb keyboard.
![sc](https://github.com/T-Troll/alienfx-tools/assets/20698735/dcca8493-ec58-41f9-a4c4-1044e60991d4)

**Comment by T-Troll** [comment]
It's detected, but have no name (i'll add check for this case).
And yes, autodetect not available for your device (no one share mappoings for me), so you need to proceed to manual setup - read beginner's guide.

**Comment by dynamiszmx** [comment]
Thank you just spend some time map the keyboard.
