### ISSUE TITLE
Dell G15 5525 RGB broken zone by AlienFX-cli

### ISSUE THREAD

**Issue by gjarro** [T-Troll/alienfx-tools#428]
The problem:
I was configuring the RGB zones on my G15 with AlienFX Control and it literally has locked the third zone of my RGB on a color I had set before. It does change the color but doesn't stay as it should, as it flickers back every some miliseconds to the color.
The steps to reproduce are literally trying to set up the lights using the color 64,0,28 on G15 5525, and I've seen a similar problem on a G15 5530 from my country, but in his case, it was the first zone of the keyboard, but same color.

Edit: I've forgot to mention that I've tried uninstalling and reinstalling both AlienFX and AWCC twice, reseted the CMOS by pressing power button without the battery for 15s, reinstalled BIOS and even tried a Windows clean install with a Windows To Go external SSD.

I've attached a slow-mo GIF of the problem below:
![20240522_194159_1-ezgif com-optimize](https://github.com/T-Troll/alienfx-tools/assets/170580349/0f1d057d-7d73-42f4-b217-35eaacf863b8)
![20240522_200144](https://github.com/T-Troll/alienfx-tools/assets/170580349/2d11e923-49c6-4f45-97bd-4a64490870ce)
![20240522_200233](https://github.com/T-Troll/alienfx-tools/assets/170580349/1cebae0d-42bc-4944-8b72-69b515e19364)

System:
 - Model: Dell G15 5525, BIOS 1.16.1
 - Model details: RTX 3060 with 4-zone RGB ABNT2 keyboard
 - OS: Windows 11 stable 23H2

**Comment by ccrdmtr** [comment]
Hello, im the owner of the 5530 with the same problem, RTX 4050 model.

**Comment by T-Troll** [comment]
Configs doesn't change hardware configuration into chip, as well as BIOS reset.
So, check some things:
1. You don't set this zone to "Pulse" at Color tab
2. You don't set this zone to "Power button" at Devices tab

In case this doesn't help - reset light chip - see project [readme](https://github.com/T-Troll/alienfx-tools?tab=readme-ov-file#light-system-reset) about how to do this.

**Comment by gjarro** [comment]
I've downloaded an older version of the program, the 8.5, and tried messing up with some settings, and then it went back to normal, both on AlienFX and AWCC. It seems it could possibly be a bug from 8.6.
