### ISSUE TITLE
Fans don't spin using manual mode on G15 AMD (UPDATE: it works on old AlienFX versions)

### ISSUE THREAD

**Issue by sa-zrx** [T-Troll/alienfx-tools#429]
Every time I try to set my fans to spin according to the setting, they literally go to the lowest RPM possible and don't spin. Also, every time it tries to set the boost, my audio pops and there's a frame skip on my screen, as if it's trying to change the entire power mode.
I've tried to use manual mode on this laptop since I got it, and it had BIOS 1.8.0, and it's now on 1.16.1, none of the BIOS I've tested ever worked. Also, I've tried pretty much every version of AlienFX Tools since 8.3.0.

![image](https://github.com/T-Troll/alienfx-tools/assets/76273716/38ef3b79-696f-4eab-a821-51543a038707)
![image](https://github.com/T-Troll/alienfx-tools/assets/76273716/7d0b9848-66a4-42ff-9113-4e1a8f048655)

As the images below suggest, the boost dot alternates between red and green. Using the command "alienfan-cli.exe unlock" gets me exactly the same result. But, if I put a really high polling rate, the program is able to set the speed as it's intended to, yet it spins down to zero as soon as the time defined in ms passes and then goes up again depending on the temperature. For example, I've tried setting a different curve here:

![image](https://github.com/T-Troll/alienfx-tools/assets/76273716/f687602f-3b70-4780-9763-66c4135ae8d0)

Here's the system ID detected by the program:

![image](https://github.com/T-Troll/alienfx-tools/assets/76273716/27dc495f-4757-44eb-bf2e-d78ab942a1b3)

I'm totally open to create any dump of this system if needed.
My system:
Dell G15 5525, (R7 6800H with RTX 3060)
Windows 11 23H2 stable
BIOS 1.16.1

**Comment by sa-zrx** [comment]
I've tried downloading AlienFX 8.1.4 and somehow, the fan control works perfectly on this version. It would be very appreciated if this problem is investigated. Also, from 8.2.0 onwards, it absolutely stops working on my laptop.
![image](https://github.com/T-Troll/alienfx-tools/assets/76273716/f0e63eba-a3bf-4cd0-9363-83d4564a25c6)
![image](https://github.com/T-Troll/alienfx-tools/assets/76273716/dc17e527-276e-4be8-9742-c1d15d741116)
Both GPU and CPU fans are working now accordingly to the curves and absolutely no audio pops of frame skips on my machine.

**Comment by T-Troll** [comment]
Thanks. I'll check it then have a little time...

**Comment by sa-zrx** [comment]
Issue fixed as of latest version (8.6.1.1)
