### ISSUE TITLE
8.6.1.1 - Dell G16 7630 - G mode issue

### ISSUE THREAD

**Issue by Blackwolf14** [T-Troll/alienfx-tools#435]
I have a Dell G16 7630. I am constantly stuttering in G mode on 8.6.1.1. No issues with 8.6.1.

**Comment by T-Troll** [comment]
I need your SystemID, please. Open Admin CMD, run `alienfan-cli getpower`

**Comment by Blackwolf14** [comment]
![3bpb0nx](https://github.com/user-attachments/assets/4703b3fe-2cfb-4abb-981e-c8d2fa493e3e)

**Comment by T-Troll** [comment]
I fix this bug into 8.6.1.2. Check, please.

**Comment by Blackwolf14** [comment]
Thanks, it's fixed.
