### ISSUE TITLE
fan can't go under 2800 even I put curve to boost 0

### ISSUE THREAD

**Issue by xli659** [T-Troll/alienfx-tools#438]
### Discussed in https://github.com/T-Troll/alienfx-tools/discussions/437

<div type='discussions-op-text'>

<sup>Originally posted by **xli659** July 29, 2024</sup>
When doing the manually fan control, the lowest fan will stay around 2800 RPM (48% fan speed), even when I put the curve boost to zero. It only can control fan speed above 2800 RPM. Is this expected behavior? I am on M16 R2. Is this model supported? </div>

**Comment by Artx-II** [comment]
I'm having kind of the same issue.

My fans wont go bellow 2300 rpm no matter which how I configure it, interestingly thought, when I change the power mode to any of the "Level 16X", it drops to 0 rpm

I am not sure if this is a bug or I'm not understanding how this works.

**Comment by T-Troll** [comment]
It's a common situation.
This gear doesn't have direct fan control, but indirect. So you can set RPM higher, then BIOS suggest, but not lower.
It's for good, in fact.

All power modes have different PASV (Passive) temperature points, so some of them turn fans off, some not.

Hint: I have a keyboard shortcuts to switch modes (CTRL+ALT+digit).
