### ISSUE TITLE
AlienFX Monitor isn't updated?

### ISSUE THREAD

**Issue by neoacevedo** [T-Troll/alienfx-tools#448]
I recently downloaded the 9.0.0.0 MSI version of alienfx-tools. The AlienFX Monitor and AlienFan Control are updated to that version number, but when I openopening AlienFX Monitor it launches the new version update notification and when I check the about menu, this is in the previous version.

![imagen](https://github.com/user-attachments/assets/e9e7b67e-2ad6-4a76-95f0-398a50069c56)
![imagen](https://github.com/user-attachments/assets/dd8664a3-bd59-4792-88c8-c09d2c8bbd10)
![imagen](https://github.com/user-attachments/assets/bc2c184f-0a78-4fc2-9a1c-bb1577430a20)

**Comment by T-Troll** [comment]
I check - MSI have correct version for all tools.
Your situation can be met if some tools run during update and install can't stop it.
So try to stop all tools and run msi again.

**Comment by neoacevedo** [comment]
@T-Troll it didn't work. 

I didn't have any AlienFX tool running and I disabled the Windows Defender to check if it was doing something. I had to uninstall the software and install it again to get the latest version for AlienFX Monitor.
