### ISSUE TITLE
Alienfan-CLI v9.0.0.1 "Hardware not compatible."

### ISSUE THREAD

**Issue by hangukhiphop** [T-Troll/alienfx-tools#452]
**Describe the bug**

CLI application says my hardware is incompatible for fan control, which is odd because hwinfo64 has a feature to set the fan speed manually and it works. I was hoping for something more integrated...

**To Reproduce**
To reproduce, simply open terminal in AlienFX Tools directory and enter "alienfan-cli" and the message will appear whether theres a command or not

**System (please complete the following information):**
 - Model: Alienware 17
 - OS: Windows 10 Enterprise

**Comment by T-Troll** [comment]
Yes, older Alienware (prior to m-series) does not support the control method i use.
It can be controlled directly via FanControl or HWInfo.
Newer systems can not compatible with direct control, instead.
