### ISSUE TITLE
Way to disable TCC in Fan Control - I use ThrottleStop for this

### ISSUE THREAD

**Issue by amarildolsouza** [T-Troll/alienfx-tools#456]
---

**Is your feature request related to a problem? Please describe.**

The TCC feature in Fan Control is overriding the same option in ThrottleStop.
<img width="541" alt="Screenshot 2024-09-22 095357_2" src="https://github.com/user-attachments/assets/d540a67a-714e-4397-b1aa-48525ad243aa">

---

**Describe the solution you'd like**

Option to turn off TCC control. I use ThrottleStop for this.

---

**Describe alternatives you've considered**

The first value could be "Off", then 85 to 100.
<img width="269" alt="Screenshot 2024-09-22 094611_2" src="https://github.com/user-attachments/assets/5376dae9-4468-4881-9f97-6a2db4b3cc13">

---

**System (please complete the following information):**
 - Model: Alienware m16 R1
 - Model details: Intel i9-13900HX, 32GB RAM DDR5 5600, RTX 4070 8GB, 2x 2TB NVMe S70 Blade
 - OS: Windows 11 Pro

---

**Additional context**

**Comment by T-Troll** [comment]
Well... First of all, TCC can not be disabled - it's an internal feature of the CPU.
It can be reset to default value for CPU (Usually 100C for Intel, 105C for AMD).
Second point - me and TS set it using different ways - they access CPU registers directly, i'm using Dell ACPI BIOS functions for this. 
Third point.... At my gear (m16 as well), TS provide significant performance drop, so i stop using it. JFYI.

So, keep this points in mind, what do you want to have as a result?

**Comment by amarildolsouza** [comment]
> Well... First of all, TCC can not be disabled - it's an internal feature of the CPU. It can be reset to default value for CPU (Usually 100C for Intel, 105C for AMD). Second point - me and TS set it using different ways - they access CPU registers directly, i'm using Dell ACPI BIOS functions for this. Third point.... At my gear (m16 as well), TS provide significant performance drop, so i stop using it. JFYI.
> 
> So, keep this points in mind, what do you want to have as a result?

By "Off" I mean "Fan Control" stop control TCC and let, for example, ThrottleStop control it.

But I will follow your advise and will disable on ThrottleStop and will 
test on Fan Control.
