### ISSUE TITLE
AW3423DWF not detected

### ISSUE THREAD

**Issue by panki27** [T-Troll/alienfx-tools#461]
Hi,

I just setup alienfx-tools and tried it out, but my AW3423DWF is not detected.

```
$ alienfx-cli.exe probe
alienfx-cli v9.0.1
Dell API ready, 1 devices found.
===== Device VID_187c, PID_100e =====
+++++ Detected as: Realtek HID Device, APIv9 +++++

$ alienfx-cli.exe status
alienfx-cli v9.0.1
Dell API ready, 1 devices found.
Device #0 - Realtek HID Device, VID#6268, PID#4110, APIv9, 0 lights
Done.
```

Anything else I can do to debug this? Thanks in advance :)

**Comment by T-Troll** [comment]
Unfortunately, APIv9 (dwF monitors) is still under development. It detected into my tools (as you can see), but can't be controlled yet.
Please wait for updates.

**Comment by panki27** [comment]
Thank you for taking the time to answer, if you need help in researching this let me know.

**Comment by T-Troll** [comment]
They add some kind of encryption into commands.
Now we have international group hacking it, but this took time.
Ask @Fefedu973 for details.

**Comment by TheMasterDingo** [comment]
Is there any chance for this monitor to be supported in the near future? Thanks

**Comment by T-Troll** [comment]
Yes, we are working on it, but no forecast about dates, sorry.

**Comment by TheMasterDingo** [comment]
Cool, thanks

**Comment by Fefedu973** [comment]
The reverse engineering work has been done, we now need to implement it into the software in a good way

**Comment by t56k** [comment]
Hi all, any update here? I get overheating warnings on NixOS, I suspect the fan isn't spinning up

**Comment by Fefedu973** [comment]
It is supported in openrgb and Signal rgb btw
(You just need my plugin)
