### ISSUE TITLE
Fan control not working on X14R2?

### ISSUE THREAD

**Issue by dynamiszmx** [T-Troll/alienfx-tools#464]
The fan curve in manual mode behaves oddly on my Alienware X14R2. I've set a flat line with a boost of 10 as long as the temperature stays below 80 degrees, but the fan still speeds up as the temperature rises.

The boost remains constant at 10, but the actual fan speed—the percentage displayed next to the boost number—still increases. Am I misunderstanding how this function works?

![image](https://github.com/user-attachments/assets/f5ee5355-068e-45e7-87d2-5969118e30f3)

System 
 - Model: Alienware X14 R2
 - OS:  Windows 11

**Comment by T-Troll** [comment]
Yes, this is correct.
We only have indirect fan control for our gear, so boost can only increase RPM above BIOS settings (but still keep it not so loud).

Use power modes for quiet operation (but it will cost lower TDP limits).

**Comment by dynamiszmx** [comment]
thank you!

> Yes, this is correct. We only have indirect fan control for our gear, so boost can only increase RPM above BIOS settings (but still keep it not so loud).
> 
> Use power modes for quiet operation (but it will cost lower TDP limits).
