### ISSUE TITLE
Alienware AW610M mouse support.

### ISSUE THREAD

**Issue by T-Troll** [T-Troll/alienfx-tools#73]
VID_0461&PID_4EC0 (Primax Electronics).
Software component for AWCC.

**Comment by T-Troll** [comment]
Next step:
- Install USBPcap.
- Run USBPcap, select the device this mouse attached into, choose filename (like `mouse.pcap`).
- Run AWCC
- Set some mouse light(s) for some basic colors (like red, green, blue) 1-3 times.
- Stop USBPcap
- Attach USBPcap log file here.

**Comment by Billybobertjoe** [comment]
[mouse.zip](https://github.com/T-Troll/alienfx-tools/files/7516937/mouse.zip)

**Comment by Billybobertjoe** [comment]
i had to compress it because it said the file itself wasnt supported

**Comment by T-Troll** [comment]
Thank you. Let me check.

**Comment by T-Troll** [comment]
So, at first glance:
- You have m15, not M15 with per-key RGB keyboard.
- You notebook have 2 light devices - one Alienware v4 - tron, power button; one Darfon v5 - RGB keyboard. Both supported.
- I got you mouse lights input, but need some time for analysis. You can help me telling what exactly you do (which lite which color), protocol is uncommon.

Now i going for analysis, you can help me providing more logs (the same way) for different operations:
- Go dark, Go light, Go dim, undim (for mouse only, it's ok if for all devices as well) (log 2).
- Set one, the same mouse light for different light effects - color (like here), then pulse red-green, then morph green-blue (if you have other effects - it's nice to do it as well, but use different basic color combination for all of them).

**Comment by T-Troll** [comment]
PS: You can install WireShark and take a look inside logs yourself, if you want - you devices:
- 1.4.0 - Alienware chip,
- 1.7.0 - Darfon chip,
- 1.11.4 - Mouse chip.

**Comment by Billybobertjoe** [comment]
[mouse1.zip](https://github.com/T-Troll/alienfx-tools/files/7517267/mouse1.zip)

**Comment by T-Troll** [comment]
Here is your mouse basic protocol:
```
Commands:
ack:
c002

color:
401a07000aff0000
-------- Command
        -- Light ID
          ------ Color

control:
40100c000164002aaaff
-------- Command
        -- ???
          -- Brightness
            --------??? (always the same)

update:
40600700c04e000001
update2:
40600700c04e000100

report:
4003010001

Command chain:
report->ack->[color->update]->report->control->update2 - bulk color set
report->control - set device brightness
```

**Comment by T-Troll** [comment]
What's next?
First, let me implement it (1-2 days), then we go to testing:
- I will share simple app for you, the main goal is to check device detected correctly.
- I will share simple app which set some lights. The goal is to make sure device accept commands and execute it correctly.
- Then i release tools with basic support and continue with effects (easier).

So wait to me until i publish test apps for you.

**Comment by T-Troll** [comment]
So, this is first test app - [AlienFXDeviceTester.exe.zip](https://github.com/T-Troll/alienfx-tools/files/7517647/AlienFXDeviceTester.exe.zip)

Can you, please:
- Open command line (cmd)
- Run it
- Copy all output it provide (it could find about 6 devices)
- Paste it here

I will check device properties and make sure it detected correctly.
T.I.A!

**Comment by Billybobertjoe** [comment]
[Uploading AlienFXTester output.txt…]()

**Comment by Billybobertjoe** [comment]
[AlienFXTester output.txt](https://github.com/T-Troll/alienfx-tools/files/7528751/AlienFXTester.output.txt)

**Comment by T-Troll** [comment]
Great, thank you!
So detection is correct.
BTW, you have 10(!) lights at mouse - indexes from 1 to 10.

So, stage 2. Run [this app](https://github.com/T-Troll/alienfx-tools/files/7531258/AlienFX.Sample.App.exe.zip), please (from the command line as well).
What i need to know:
1. Is device init ok? (it should output about it)
2. Is device call OK? (it should have output like "SetColor result: X". If X = 1 it's ok, if it's 0 - it requires more tests).
3. If both ok, did it change light color (it should set light#1 to blue, and light#2 to cyan)?

In case all 3 points ok, we have basic support, but most probably we are fail at #2. In this case, i will provide you another testing app, with the different approach.

**Comment by Billybobertjoe** [comment]
both failed

**Comment by T-Troll** [comment]
So, did it tells "Can't init device!" or just 0 in results and lights not changed?

**Comment by T-Troll** [comment]
Ok, anyway, let's try this one:
[AlienFX Sample App.exe.zip](https://github.com/T-Troll/alienfx-tools/files/7531573/AlienFX.Sample.App.exe.zip)
The task is the same.

**Comment by Billybobertjoe** [comment]
3 device(s) detected.
VID: 0x461, PID: 0x4ec0, API v7
API v7
Let's try to set some colors...
SetColor result: 0
SetColor 2 result: 0

**Comment by Billybobertjoe** [comment]
seems to have failed

**Comment by T-Troll** [comment]
Yes. %-(
Result 0 means driver didn't accept the command.
Ok, let's try this way - [AlienFX Sample App.exe.zip](https://github.com/T-Troll/alienfx-tools/files/7533240/AlienFX.Sample.App.exe.zip)

Task is the same. If fail again, i provide another one, but if next one fail - it will be paused until i configure out the issue.

**Comment by Billybobertjoe** [comment]
3 device(s) detected.
VID: 0x461, PID: 0x4ec0, API v7
API v7
Let's try to set some colors...
SetColor result: 1
SetColor 2 result: 1

**Comment by Billybobertjoe** [comment]
i didnt see any color change on my mouse or keyboard though

**Comment by T-Troll** [comment]
Aha! And did colors changed (on mouse only)? Ok, got it.

Anyway, please, try this one - [AlienFX Sample App.exe.zip](https://github.com/T-Troll/alienfx-tools/files/7533264/AlienFX.Sample.App.exe.zip)

One of them should change colors.

**Comment by Billybobertjoe** [comment]
3 device(s) detected.
VID: 0x461, PID: 0x4ec0, API v7
API v7
Let's try to set some colors...
SetColor result: 0, error 57
SetColor 2 result: 0, error 57

**Comment by Billybobertjoe** [comment]
hmm

**Comment by T-Troll** [comment]
Hardware error.
Ok, what about this (i don't need log, only error code if any non-zero and result) - [AlienFX Sample App.exe.zip](https://github.com/T-Troll/alienfx-tools/files/7533273/AlienFX.Sample.App.exe.zip)

**Comment by T-Troll** [comment]
By the way... Stop AWCC service first, it can alter colors.

**Comment by Billybobertjoe** [comment]
oh ok

**Comment by Billybobertjoe** [comment]
VID: 0x461, PID: 0x4ec0, API v7
API v7
Let's try to set some colors...
SetColor result: 1, error 0
SetColor 2 result: 1, error 0

**Comment by Billybobertjoe** [comment]
still no color change

**Comment by Billybobertjoe** [comment]
my keyboar and mouse are changing colors with AWCC service disabled. not from the app u sent though. just fro awcc spectrum setting

**Comment by Billybobertjoe** [comment]
what now?

**Comment by T-Troll** [comment]
Ok, now on pause - let me think more.
I'll share another test app later on.
Yes, hardware effects not depends on AWCC... Hmm... But can interfere with color set!
Can you disable effects on mouse and check again?

**Comment by Billybobertjoe** [comment]
how do i disable the effects?

**Comment by T-Troll** [comment]
Open AWCC, select mouse and choose global effect (or per-button, don't sure it has global) for "color".

**Comment by T-Troll** [comment]
Also, please check another version (but first previous one!): 
[AlienFX Sample App.exe.zip](https://github.com/T-Troll/alienfx-tools/files/7533292/AlienFX.Sample.App.exe.zip)

**Comment by Billybobertjoe** [comment]
i see no "global effect" or "per-button" option

**Comment by T-Troll** [comment]
They name it "static button". Left one above colors circle.

**Comment by Billybobertjoe** [comment]
I.. still dont see anything like that. Example picture?

**Comment by T-Troll** [comment]
![image](https://user-images.githubusercontent.com/51940412/141671928-8ae6881f-4e15-413c-8ef6-33116a2b821f.png)

**Comment by Billybobertjoe** [comment]
![Screenshot 2021-11-14 003357](https://user-images.githubusercontent.com/70166353/141672066-29c336d4-1a16-4f7a-9795-a17695be1e3c.png)

**Comment by Billybobertjoe** [comment]
im on version 5.4.7.0

**Comment by T-Troll** [comment]
Should be OK. Maybe in "Settings" now....
Anyway, let's try - both previous and last versions.

**Comment by Billybobertjoe** [comment]
No luck

**Comment by T-Troll** [comment]
Does it return `Result: 0` or just don't change colors?

**Comment by Billybobertjoe** [comment]
doesnt change colors

**Comment by Billybobertjoe** [comment]
Be heard that dell removed the “enable 3rd party access” setting. Idk if that has something to do with this

**Comment by T-Troll** [comment]
So, let's do another round.

Use this test app - [AlienFX Sample App.exe.zip](https://github.com/T-Troll/alienfx-tools/files/7573245/AlienFX.Sample.App.exe.zip)

Please, follow this process:
- Set MOUSE to steady color (no effects) into AWCC.
- Close AWCC, go to "Services", stop "AWCCService" (no, just close AWCC is not enough for now).
- Run app.
- If colors not changed, look at "SetColor result:" values. If it's zero, we are deep in troubles. But if it's 1, let's check more:
  - Start USBPcap (the same way like before)
  - Run app
  - Stop USBPcap, send me the log to understand what's going wrong at low level.

> I heard that dell removed the “enable 3rd party access” setting. Idk if that has something to do with this

If they enable it by default, it's not an issue. If they remove support - i have their library emulation ^_^

**Comment by Billybobertjoe** [comment]
[mouselighttest.zip](https://github.com/T-Troll/alienfx-tools/files/7573339/mouselighttest.zip)

**Comment by Billybobertjoe** [comment]
theres the log

**Comment by T-Troll** [comment]
Well... Good news - commands coming into device successfully and in right form.
Now i need to check is this CORRECT commands, and maybe i miss the protocol format and need to study more.

**Comment by T-Troll** [comment]
Seems like i found an issue.

Let's try this (keep your eye at "SetColor result:", please):
[AlienFX Sample App.exe.zip](https://github.com/T-Troll/alienfx-tools/files/7573467/AlienFX.Sample.App.exe.zip)

**Comment by Billybobertjoe** [comment]
3 device(s) detected.
VID: 0x461, PID: 0x4ec0, API v7
Let's try to set some colors...
SetColor result: 1, error 0
SetColor 2 result: 1, error 0

after disabling the AWCC service, the colors changed on my mouse. are the lights on my keyboard supposed to also change too?

**Comment by Billybobertjoe** [comment]
so it worked!!!

**Comment by T-Troll** [comment]
Greeeat! So we hack it!

What we need to do next:
- First, i drop you another test app - i need to check lights off/on/dim works well.
- If OK, i release new package with BASIC mouse support, and you can use it.
- Then we test light effects and release full support version.

In fact, this is about 85% of full support for now.

No, your keyboard colors should not change, as you can see, i use mouse device only.
But both keyboard and tron already supported, so just download and start last tools release, define light names, and have fun.

After we are finish support, i tickle Aurora guys about AW support as well.

**Comment by Billybobertjoe** [comment]
Ok ill do this tomorrow

**Comment by Billybobertjoe** [comment]
when can we start? also, is there a way i can integrate this into aurora?

**Comment by T-Troll** [comment]
I have GMT+7. ^_^

Ok, let's do the latest test in this round. Here is the app: [AlienFX Sample App.exe.zip](https://github.com/T-Troll/alienfx-tools/files/7577259/AlienFX.Sample.App.exe.zip)

As usual, disable awcc service and start it. What it should do:
- Set 2 mouse lights to white.
- Wait you to press Enter.
- Off all lights and wait for Enter.
- Dim (to half) all lights and wait for Enter.
- Return lights to full brightness and... wait for Enter pressed.

If all steps doing well (keep your eye what color lights have after it's back on), that's all for basic support.

About Aurora, yes, but some effort needed - they use slightly weird structures for light modules.

**Comment by Billybobertjoe** [comment]
3 device(s) detected.
VID: 0x461, PID: 0x4ec0, API v7
Let's try to set some colors...
SetColor result: 1, error 0
SetColor 2 result: 1, error 0
Ok, let's try to set lights off...

Now set for half brightness...


... then return back to full...
Done!

**Comment by Billybobertjoe** [comment]
it all worked fine

**Comment by Billybobertjoe** [comment]
at the end, the color changed to blue

**Comment by Billybobertjoe** [comment]
i had it set to white at the start

**Comment by T-Troll** [comment]
> at the end, the color changed to blue

Is it changed to blue after "Now set for half brightness..." or after app finished?

If first - i need to modify light resume, if second - it means AWCC change it (maybe you forget to stop AWCCService).

**Comment by Billybobertjoe** [comment]
It changes it as soon as i start the app

**Comment by T-Troll** [comment]
I mean, change from white back to blue?

**Comment by Billybobertjoe** [comment]
Yes

**Comment by Billybobertjoe** [comment]
Oh, no. I manually set it to white before starting the app so that the change was obvious

**Comment by T-Troll** [comment]
Crazy. I set it to white into the app!

**Comment by Billybobertjoe** [comment]
Weird

**Comment by Billybobertjoe** [comment]
So what now?

**Comment by T-Troll** [comment]
Another test app - [AlienFX Sample App.exe.zip](https://github.com/T-Troll/alienfx-tools/files/7577757/AlienFX.Sample.App.exe.zip)

What it should do:
- Set first color to red, second to green, third to blue.
- Off lights
- Dim lights
- Undim lights

Please, check, does it work as intended?

**Comment by Billybobertjoe** [comment]
Everything worked except for the changing colors part. None of the colors changed

**Comment by T-Troll** [comment]
Fck... But it did it before. NB: Only mouse colors should be changed!
Ok, let me think.

**Comment by Billybobertjoe** [comment]
ok

**Comment by Billybobertjoe** [comment]
wait...

**Comment by Billybobertjoe** [comment]
it seems to like the color blue

**Comment by Billybobertjoe** [comment]
if it does change colors, it changes to light blue. not white or red. just light blue on the whole mouse

**Comment by T-Troll** [comment]
Got it. Try this one - [AlienFX Sample App.exe.zip](https://github.com/T-Troll/alienfx-tools/files/7578221/AlienFX.Sample.App.exe.zip), please.

Method is the same as before, but if i right, it will not off/dim ALL mouse lights...

**Comment by Billybobertjoe** [comment]
Right when i start the app, the light turns green. When it is at half brightness, the light is white. It is also white at full brightness

**Comment by T-Troll** [comment]
Correct. 

By the way, it's 4 different effect types available.

Great, now i integrate it into tools, then share beta release for you for testing.

PS: By the way, Aurora have Dell LightFX wrapper support. And i have LightFX emulator. I'll write you about how to use it later on.

**Comment by Billybobertjoe** [comment]
ok! CANT WAIT!!!

**Comment by T-Troll** [comment]
Can you please check effect modes meanwhile?

Here is the test app: [AlienFX Sample App.exe.zip](https://github.com/T-Troll/alienfx-tools/files/7584875/AlienFX.Sample.App.exe.zip)

You need to run it, it will set light #1 to colors between green and blue and effect to given mode (from 1 to 7), then wait for input.
Check what light doing (1 should be steady color, 2-5 i see into your logs but have no idea what is it, 6-7 worth to check just for sure), then write it down for me and press enter for next mode.

**Comment by T-Troll** [comment]
I included support for mouses at [latest release](https://github.com/T-Troll/alienfx-tools/releases/tag/5.3.0).

Hope effects will work as well.

**Comment by Billybobertjoe** [comment]
i can no longer add effects with ur app.not even with the keyboard anymore

**Comment by Billybobertjoe** [comment]
it worked fine with the previouse version. now the drop down box is greyed out

**Comment by T-Troll** [comment]
Did you check effect types using sample app? Do it, please!

**Comment by Billybobertjoe** [comment]
How?

**Comment by T-Troll** [comment]
> Can you please check effect modes meanwhile?
> 
> Here is the test app: [AlienFX Sample App.exe.zip](https://github.com/T-Troll/alienfx-tools/files/7584875/AlienFX.Sample.App.exe.zip)
> 
> You need to run it, it will set light #1 to colors between green and blue and effect to given mode (from 1 to 7), then wait for input. Check what light doing (1 should be steady color, 2-5 i see into your logs but have no idea what is it, 6-7 worth to check just for sure), then write it down for me and press enter for next mode.

**Comment by Billybobertjoe** [comment]
[mouse results.txt](https://github.com/T-Troll/alienfx-tools/files/7592818/mouse.results.txt)

**Comment by Billybobertjoe** [comment]
https://drive.google.com/file/d/1m_mk41JoY4Jc1CD0B_O76H4tkI68BItB/view?usp=sharing

**Comment by Billybobertjoe** [comment]
youll understand what the google drive link is for afteer reading the txt file

**Comment by T-Troll** [comment]
Got it.
So final mapping codes to app:
1. Color
2. Breathing
3. Morph
4. Spectrum
5. Pulse
6. Rainbow

BTW, seems like mode 6 is not supported by AWCC. ^_^

Ok, we do it, i'll add code mappings into SDK at next release!
Thank you for help!

**Comment by Billybobertjoe** [comment]
Are you sure it isn't supported by AWCC? i use that setting all the time for my mouse lights.

**Comment by T-Troll** [comment]
I was not existed into your logs, so maybe they set it as default at device start.

**Comment by Billybobertjoe** [comment]
It is called “color wave” i think

**Comment by T-Troll** [comment]
Can you, please, check all mouse functions working now and close this issue if it's ok?

PS: Don't forget to add 2nd mouse light, i see you use one (ID0) only, but your mouse have 2 (also ID1, i use it for testing before).

**Comment by Billybobertjoe** [comment]
Can we continue this on discord or no?

**Comment by T-Troll** [comment]
This topic is about mice, not about overall and keyboard issues.
Of course, we can continue other discussions in Discord.

**Comment by Billybobertjoe** [comment]
When i try to set the other mouse light as a different color, it only acts like there is one light and sets to one color, not separate colors

**Comment by Billybobertjoe** [comment]
![image](https://user-images.githubusercontent.com/70166353/144556620-14c77ac9-22f9-47a3-b96b-035a957e719c.jpg)
![image](https://user-images.githubusercontent.com/70166353/144556659-cf1bea50-3813-4d8d-81b0-31108296fd97.jpg)
![Uploading image.jpg…]()

**Comment by Billybobertjoe** [comment]
![image](https://user-images.githubusercontent.com/70166353/144557945-8c46b3f0-6ef3-44ff-81a1-3b4fa80d4db8.jpeg)![image](https://user-images.githubusercontent.com/70166353/144558016-ac2c5a2e-51e2-4526-8a54-fbe3c5fb3403.jpeg)![image](https://user-images.githubusercontent.com/70166353/144558066-b4888120-2c09-4f1f-8c65-ce88069de7d7.jpeg)

**Comment by T-Troll** [comment]
So light ID0 did not work. Ok, let me check.
