### ISSUE TITLE
Fan Boost Value Changed

### ISSUE THREAD

**Issue by Hellohi3654** [T-Troll/alienfx-tools#75]
Hey just wondering if you would be able to set the max fan boost to 170

I'm not sure what has changed but it seems now that boost 170 is now the max RPM for my fans
Boost 160 is about 5100RPM while boost 170 is around 5700RPM

Thanks

Btw if you have forgotten which laptop I have it's the Dell G5 15 (AMD)
Thanks again

**Comment by T-Troll** [comment]
Even better. Latest release have special `alienfan-overboost` tool.
Run it, and it set all boosts to maximal possible level (check readme_alienfan for details).

**Comment by T-Troll** [comment]
PS: and no, boost can't be more, then 255 (it's a byte value inside BIOS).

**Comment by Hellohi3654** [comment]
ok thanks

**Comment by Hellohi3654** [comment]
> Even better. Latest release have special `alienfan-overboost` tool. Run it, and it set all boosts to maximal possible level (check readme_alienfan for details).

Awesome very helpful
